### ISSUE TITLE
[Feature Request] Wyze Thermostat

### ISSUE THREAD

**Issue by AndrewLemons** [JoshuaMulliken/ha-wyzeapi#103]
The Wyze Thermostat has just been released. I currently have one, and am looking for it to be supported by Home Assistant.

I'm not sure whether control of the thermostat is possible. However, I do know for sure that some of the sensors can be read from. Here are the properties mapped to their values (the ones I currently know about, at least)

| Property | Value |
|-|-|
| `P2602` | State `1 = Home` `2 = Away` `3 = Sleep` | 
| `P2603` | Mode `0 = Off` `1 = Heat` `2 = Cool` `3 = Auto` |
| `P2604` | Cool to |
| `P2605` | Heat to |
| `P2606` | Current temperature |
| `P2607` | Units `0 = C` `1 = F` |

Here is an example response
``` JSON
[
  { "pid": "P2601", "value": "0", "ts": 1608420519245 },
  { "pid": "P2602", "value": "1", "ts": 1608430107789 },
  { "pid": "P2603", "value": "3", "ts": 1608430244679 },
  { "pid": "P2604", "value": "73", "ts": 1608430244619 },
  { "pid": "P2605", "value": "68", "ts": 1608430244632 },
  { "pid": "P2606", "value": "68.3", "ts": 1608424879880 },
  { "pid": "P2607", "value": "1", "ts": 1608428378629 },
  { "pid": "P5", "value": "1", "ts": 1608418922630 }
]
```
The information above was retrieved using the Node JS package for the API. I don't know if it alters the raw response, so take it as you will.

As a small side note, the MAC address of the device is oddly long. I was under the impression that all MACs were of a common length, but apparently not. Example `CO_EA1_xxxxxxxxxxxxxxxxxxxxxxxxxxx`.

I will gladly study the code base to see if I can implement this myself. But, if anyone else (who already knows what they are doing) can add support, that would be great.

-Andrew

**Comment by jfarmer08** [comment]
You need to get the full output from get_object_list before someone could add it. 

You could also share the device and someone could open there app to get the result of get object.

**Comment by yfaber** [comment]
Hey bud, have you had the chance to play with the lock anymore?

**Comment by AndrewLemons** [comment]
Here ya' go.

``` json
{
"mac":"CO_EA1_xxxxxxxxxxxxxxxxxxxxxxxx",
"first_activation_ts":1608418333000,
"first_binding_ts":1608418333000,
"enr":"",
"nickname":"Upstairs Thermostat",
"timezone_name":"UTC",
"product_model":"CO_EA1",
"product_model_logo_url":"",
"product_type":"Thermostat",
"hardware_ver":"0.0.0.0",
"firmware_ver":"1.0.0",
"user_role":1,
"binding_user_nickname":"xxx",
"conn_state":1,
"conn_state_ts":1608522611426,
"push_switch":1,
"device_params":{},
"is_in_auto":0,
"event_master_switch":1,
"parent_device_mac":"",
"parent_device_enr":"",
"binding_ts":1608418332000,
"timezone_gmt_offset":0
}
```

**Comment by JoshuaMulliken** [comment]
Awesome I will work on this today! Thanks @AndrewLemons
