### ISSUE TITLE
[Bug] Brightness and Color don't persist turning the light on and off.

### ISSUE THREAD

**Issue by mattbilodeau** [JoshuaMulliken/ha-wyzeapi#104]
**Is your feature request related to a problem? Please describe.**

When you turn a light off and on, it doesn't keep the brightness and color temp settings it last had.  

**Describe the solution you'd like**

could we some how store the last setting of the brightness and color temperature for the entity?

**Describe alternatives you've considered**

**Additional context**

**Comment by JoshuaMulliken** [comment]
That is a great suggestion I will consider adding it to the backlog

**Comment by JoshuaMulliken** [comment]
@mattbilodeau Can you try the latest beta build and let me know if this is working like you expect it to?

**Comment by mattbilodeau** [comment]
I upgraded via HACS to the newest 4.2-beta.6, and the color temp and brightness now save, and restore at the same level,  Thank You!

**Comment by JoshuaMulliken** [comment]
@mattbilodeau Awesome!! Thanks for the feedback
