### ISSUE TITLE
[Feature Request] Outdoor Plug Support

### ISSUE THREAD

**Issue by dvanderb** [JoshuaMulliken/ha-wyzeapi#110]
Wyze recently released outdoor plugs and they are just switches on the platform.  Adding support is as easy as adding an or to the device list call to alias "Plug" and "OutdoorPlug".

**Comment by JoshuaMulliken** [comment]
Yay finally an easy one to add! I have a pull request open to add this

**Comment by JoshuaMulliken** [comment]
Everyone, please install https://github.com/JoshuaMulliken/ha-wyzeapi/releases/tag/v0.5.14-beta.1 and let me know if it works so that I can make an official release for everyone.
