### ISSUE TITLE
Error adding Add-On

### ISSUE THREAD

**Issue by bulldog65** [JoshuaMulliken/ha-wyzeapi#112]
expected a URL @ data['addons_repositories'][1]. Got ' https://github.com/JoshuaMulliken/ha-wyzeapi'

**Comment by JoshuaMulliken** [comment]
I am sorry but what is the context behind this? Have you followed the instructions in the readme?

**Comment by bulldog65** [comment]
That is the error I got when following the Highly Recommended Approach.
Supervisor -> Add-on Store -> Repositories -> Manage add-on repositories ->
copy/paste url from step 2.
I just now tried the Manual Installation and the following is from the logs
after restarting HA,

21-02-16 20:11:12 INFO (MainThread) [supervisor.store.git] Cloning
add-on https://github.com/JoshuaMulliken/ha-wyzeapi repository21-02-16
20:11:13 ERROR (MainThread) [supervisor.store]
https://github.com/JoshuaMulliken/ha-wyzeapi is not a valid add-on
repository21-02-16 20:11:13 WARNING (MainThread)
[supervisor.addons.validate] Add-on config 'auto_uart' is deprecated,
use 'uart'. Please report this to the maintainer of ESPHome21-02-16
20:11:13 ERROR (MainThread) [supervisor.utils.json] Can't read json
from /data/addons/git/4824be1f/repository.json: [Errno 2] No such file
or directory: '/data/addons/git/4824be1f/repository.json'21-02-16
20:11:13 WARNING (MainThread) [supervisor.store.data] Can't read
repository information from
/data/addons/git/4824be1f/repository.json21-02-16 20:11:13 INFO
(MainThread) [supervisor.store] Loading add-ons from store: 65 all - 0
new - 0 remove21-02-16 20:11:13 INFO (MainThread)
[supervisor.resolution.fixups.store_execute_remove] Remove invalid
Store: 4824be1f21-02-16 20:11:13 INFO (MainThread)
[supervisor.store.git] Removing custom add-on repository
https://github.com/JoshuaMulliken/ha-wyzeapi

**Comment by JoshuaMulliken** [comment]
This is not a supervisor add on. Please see this issue: https://github.com/JoshuaMulliken/ha-wyzeapi/issues/89
