### ISSUE TITLE
not logging into Wyze system and bulbs not showing up in HA

### ISSUE THREAD

**Issue by tekstein** [JoshuaMulliken/ha-wyzeapi#119]
**Describe the bug**

I recently install your repository on HA and integrate with HACS. I’ve loaded the line below with my WYZE info in the configuration.yaml. But I'm getting the error message you see below. please advise.

wyzeapi:
 username: <email for wyze>password: <password for wyze>

<img width="491" alt="Screen Shot 2021-03-13 at 4 54 38 PM" src="https://user-images.githubusercontent.com/35672015/111077349-69495b80-84be-11eb-99c2-e0aa8887ef9e.png">

**Expected behavior**

**System configuration**
System: <core-2021.3.4>
HA Version: <core-2021.3.4-->
WyzeApi Version:  
## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | America/Chicago

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4934
Installed Version | 1.11.3
Stage | running
Available Repositories | 825
Installed Repositories | 11

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 33

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.4
docker_version | 19.03.13
disk_total | 28.6 GB
disk_used | 8.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.6.0), CEC Scanner (2.4), Samba share (9.3.0), File editor (5.2.0), Mosquitto broker (5.1.1), Visual Studio Code (3.0.3), Node-RED (8.1.1), Terminal & SSH (9.0.2), Home Assistant Google Drive Backup (0.103.1), AirCast (3.0.0), AirSonos (3.0.0), Spotify Connect (0.8.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 4
views | 10
mode | storage

</details>
**configuration.yaml**

```yaml
<YOUR CONFIG HERE>
```

**home-assistant.log**

```
<Logger: homeassistant.setup
Source: custom_components/wyzeapi/wyzeapi/client.py:140 
First occurred: March 12, 2021, 10:21:08 PM (1 occurrences) 
Last logged: March 12, 2021, 10:21:08 PM

Error during setup of component wyzeapi
Traceback (most recent call last):
  File "/config/custom_components/wyzeapi/wyzeapi/client.py", line 131, in login
    self.__access_token = response_json['data']['access_token']
KeyError: 'access_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/wyzeapi/__init__.py", line 47, in async_setup
    await wyzeapi_account.login(config[DOMAIN].get(CONF_USERNAME), config[DOMAIN].get(CONF_PASSWORD))
  File "/config/custom_components/wyzeapi/wyzeapi/client.py", line 140, in login
    raise ConnectionError("Failed to login with response: {0}".format(response_json))
ConnectionError: Failed to login with response: {'ts': 1615609268079, 'code': '1001', 'msg': 'ParameterError', 'data': {}}

>
```

**Comment by JoshuaMulliken** [comment]
@tekstein do you have two factor enabled on your account?

**Comment by tekstein** [comment]
No, I don't.

**Comment by JoshuaMulliken** [comment]
Have you verified that your password is correct?

If yes then please enable debug logging and provide an updated log as described here: https://github.com/JoshuaMulliken/ha-wyzeapi#reporting-an-issue

**Comment by tekstein** [comment]
Sorry for my ￼ignorance I'm fairly new to HA. How do I do that?

**Comment by JoshuaMulliken** [comment]
What step in particular are you struggling with?

**Comment by tekstein** [comment]
I not familiar with the steps on how to do this

**Comment by brianhanifin** [comment]
I get that error when running v0.5.15-vacuum-alpha.10, but v0.5.14 works and loads my plug as expected.

**Comment by JoshuaMulliken** [comment]
@tekstein  please use the latest standard version and report back on the results

**Comment by JoshuaMulliken** [comment]
Closing due to inactivitly
