### ISSUE TITLE
[Feature Request] Cameras notifications as Motion Sensors

### ISSUE THREAD

**Issue by cuatexoft** [JoshuaMulliken/ha-wyzeapi#122]
Could you add the camera motion notifications as motions sensors?

**Comment by JoshuaMulliken** [comment]
I do not know of a way to tie into the notifications right now unfortunately

**Comment by JoshuaMulliken** [comment]
@cuatexoft I have implemented a feature where cameras can be used as motion sensors!!

Please help me test this feature by using version 2020.4.10-beta.1
