### ISSUE TITLE
[Feature Request] Support Wyze Cam v3 Spotlight

### ISSUE THREAD

**Issue by uzegonemad** [JoshuaMulliken/ha-wyzeapi#123]
It would be neat to be able to control a Wyze Cam v3's spotlight within HA.

I don't have much free time to work on it myself at the moment, but I have a spare v3 with spotlight that I can share if someone wants to work on adding support.

I tried comparing device properties with the light off versus on but it didn't seem to change. Additionally, if you turn the spotlight on, and close & reopen the app, the spotlight will have turned back off. So this may be a pipe dream.

**Comment by JoshuaMulliken** [comment]
@uzegonemad I was not aware that the v3 had a spotlight toggle. Can you describe the process in the app that it takes to turn this on?

**Comment by uzegonemad** [comment]
@JoshuaMulliken Sure, see the attached screenshots. When you're viewing a specific camera, there's a toggle next to the "Live Stream" header. Tapping it toggles the spotlight.

The curious part is that if you manually toggle on the spotlight, it turns itself off shortly after you stop viewing the live feed, leading me to wonder if it's somehow toggled via TUTK P2P and not via the Wyze API.

I haven't run a Charles session or anything though.

![IMG_9193](https://user-images.githubusercontent.com/430255/113923536-4143d400-97ae-11eb-8908-0b7585017c7c.jpg)
![IMG_9194](https://user-images.githubusercontent.com/430255/113923539-4143d400-97ae-11eb-815b-b024d40a1b7e.jpg)

**Comment by JoshuaMulliken** [comment]
Hmm, I do not see that option on my v3... Could it be the wireless outdoor cam instead?

**Comment by uzegonemad** [comment]
No, it's a v3 with the [spotlight](https://wyze.com/wyze-cam-v3-spotlight.html) accessory.

**Comment by JoshuaMulliken** [comment]
Ahh, I did not know that was a thing haha. I do not have that device but if you want to help me cover the costs I can investigate this feature.

To identify if this is possible we need to review the HTTP requests between the app and the service and see if there is one that will toggle the spotlight. My suspicion is that there is a request sent when you open the live stream and another one when you close the app or leave the page.

**Comment by uzegonemad** [comment]
@JoshuaMulliken I'll send you one. I'll shoot you an email for your mailing address.

**Comment by JoshuaMulliken** [comment]
Great!

**Comment by JoshuaMulliken** [comment]
@uzegonemad I am sorry, but I cannot find a control message for the spotlight that goes over HTTP. I suspect that it uses TUTK P2P to trigger. 

I am sorry, but I cannot support TUTK P2P at the moment because all the SDKs that I found are for C. I was excited to get this working, but It is beyond my ability to integrate this currently.

Let me know if you want me to mail the spotlight to you for use in your setup.

**Comment by uzegonemad** [comment]
@JoshuaMulliken No problem! It's yours to keep. It's a small token of appreciation for all your hard work.

I'm spending a *lot* of time with TUTK SDK lately for another project. I'll do some more digging through the SDK as time allows.

**Comment by JoshuaMulliken** [comment]
Oh, ok well, thank you!

I am going to close this issue, and we can open it up later if we find a way to add the TUTK SDK features into this integration.

**Comment by endertable** [comment]
@uzegonemad HI, have you ever figured out the Wyze TUTK by some chance?  I am trying to interface with it to get it to turn on video even when cam does not connect with the internet.  Come to thinking of it I guess you can't use TUTK without the internet, correct?

**Comment by uzegonemad** [comment]
@endertable I stopped what I was working on because I ended up finding https://github.com/mrlt8/docker-wyze-bridge which accomplished what I was trying to write on my own.
