### ISSUE TITLE
[Feature Request] Wyze Sprinkler

### ISSUE THREAD

**Issue by rickscherer** [JoshuaMulliken/ha-wyzeapi#128]
**Describe the solution you'd like**
Wyze Sprinkler integration
Would be nice to view zones, turn-on/turn-off.

**Comment by JoshuaMulliken** [comment]
I probably won't integrate this. I rent and don't have the ability to install a system like this, so I couldn't do the work. 

It's really hard if not impossible to integrate when you don't have the device unfortunately.
