### ISSUE TITLE
Sensor support

### ISSUE THREAD

**Issue by GoState** [JoshuaMulliken/ha-wyzeapi#134]
Please put sensor support back in (leave it un maintained if you like) but many of us still have working sensors and this just makes them useless...its almost as bad as when a company kills a product ;). Appreciate all your hard work on this and I get that this will become obsolete at some point but there a bunch of sensors still working and are in several automations I use everyday.  Maybe just mention they are deprecated and won't be maintained, ie.,  don't write up bugs for them.
Thanks for the consideration.

**Comment by JoshuaMulliken** [comment]
Feel free to use the previous release until you can retire them from your setup
