### ISSUE TITLE
[Feature Request] Wyze Lock

### ISSUE THREAD

**Issue by abhinav91690** [JoshuaMulliken/ha-wyzeapi#135]
It would be great to have Wyze lock integrated completely.
1.  Lock/Unlock.
2.  Door Open/Closed.
3.  Remotely locked/unlocked or Manually locked/unlocked.

**Comment by LordNex** [comment]
Agreed if someone wants to send him one to code with. I’d donate a bit.

Benjamin Powers

On Apr 8, 2021, at 12:56 PM, Abhinav Vinnakota ***@***.***> wrote:

﻿

It would be great to have Wyze lock integrated completely.

  1.  Lock/Unlock.
  2.  Door Open/Closed.
  3.  Remotely locked/unlocked or Manually locked/unlocked.

**Comment by JoshuaMulliken** [comment]
From my review of their documentation on [this page](https://wyze.com/wyze-lock) (particularly in the FAQs) it should be possible. Since you can open it remotely, there must be functionality in the app to do a request over the internet to the Wyze servers that will let you in. It is just a bit to pricey for me to investigate without the guarantee that I could get it to work.

**Comment by terrycarlin** [comment]
I will also donate to a Lock project. I would like to have at least the Lock and Door sensors implemented. I can also test the lock.

**Comment by JoshuaMulliken** [comment]
@terrycarlin @LordNex @abhinav91690  

Should I create a Lock post on BuyMeACoffee? Like I did for the Color Bulbs? 

I can say all donations for the next X weeks go toward a lock.

**Comment by LordNex** [comment]
Just so you know. I can get it to work over ZHA. Just can’t get HA to keep in sync with Wyze servers. So if someone uses the app or the remote keypad to get in, HA doesn’t know. Been playing with some templates but if we can donate to get Josh a lock to reverse engineer I think we’ll get a much better result. Only thing I use besides the lock is there cameras. But the next hardware cycle I’m not going to use Wyze unless the open up their system more.

Ben

On Apr 10, 2021, at 8:49 AM, Joshua Mulliken ***@***.***> wrote:

﻿

@terrycarlin<https://github.com/terrycarlin> @LordNex<https://github.com/LordNex> @abhinav91690<https://github.com/abhinav91690>

Should I create a Lock post on BuyMeACoffee? Like I did for the Color Bulbs?

I can say all donations for the next X weeks go toward a lock.

**Comment by terrycarlin** [comment]
Works for me. Let me know when you have it set up. Will send some money towards the lock.

**Comment by LordNex** [comment]
Ditto. Never used the service yet to setup an account but let me know when it’s ready and I’ll drop some funds in as well.

Ben

On Apr 10, 2021, at 1:46 PM, Terry Carlin ***@***.***> wrote:

﻿

Works for me. Let me know when you have it set up. Will send some money towards the lock.

**Comment by JoshuaMulliken** [comment]
I created a goal for this on my BuyMeACoffee! https://www.buymeacoffee.com/joshmulliken

**Comment by JoshuaMulliken** [comment]
I ordered the device yesterday!

**Comment by LordNex** [comment]
Sent my donation. Wasn’t a whole lot but should help. Thanks a bunch!

Also, I have one that was somewhat DOA that they let me keep. If you want to tear inter the internals, I can send you that so you don’t tear up your good one.

https://www.buymeacoffee.com/joshmulliken



On Apr 16, 2021, at 8:44 AM, Joshua Mulliken ***@***.***> wrote:

﻿

I ordered the device yesterday!

**Comment by JoshuaMulliken** [comment]
Thanks all any amount helps

**Comment by KevinVoell** [comment]
Hi @JoshuaMulliken,  
I am working on reverse engineering the Wyze API as well for a project I'm working on and happened to stumble upon this repo today.  I'm not an expert in Python, I can help you with the request and response for the lock/unlock rest calls.

API Endpoint:
POST https://yd-saas-toc.wyzecam.com/openapi/lock/v1/control

Request:
```
{
  "uuid": "<uuid (mac) of the lock>",
  "action": "<remoteLock/remoteUnlock>",
  "access_token": "<access token>",
  "key": "<the id of the key used for signing>...0ed9",
  "timestamp": "<millsecond timestamp>",
  "sign": "<md5 hash of the request json, minus this key>"
}
```

Response:
```
{
  "ReqID": "<request id>",
  "ErrNo": "<int value indicating if error occured>",
  "ErrMsg": "<error message if error occurred>"
}
```

The most complicated part of the call is signing the request, but that's not really that complicated (it still uses the older signing code, not the new stuff located in the wyze_olive-lib).  What is happening is that the json request is being serialized into a query string type format (access_token=blah&action=remoteUnlock&etc) alphabetically ordered by the key name (i.e. access_token, action, key, timestamp, uuid).  
That serialized query string is then manipulated in two ways:
1. At the beginning of the string the action and path are appended (post/openapi/lock/v1/control)
2. Then it has the signing cert value appended to the end of it (...87e8c)

So in the end you have a string that looks like this:
post/openapi/lock/v1/controlaccess_token=blah&action=remoteunlock&key=foo&timestamp=bar&uuid=deviceuuidsigningcertvalue

Put that value through an MD5 utility and URL encode the result, put that value into the sign property of the json request and send it on its way.

**Comment by JoshuaMulliken** [comment]
@KevinVoell Thank you for the contribution. That is very useful!

**Comment by JoshuaMulliken** [comment]
Lock is getting a lot closer! I have some test code working that does the signing correctly!

**Comment by JoshuaMulliken** [comment]
Hey all, please check out 2021.4.27-beta.1 and see if it is working for your instance!
