### ISSUE TITLE
New DeviceTypes

### ISSUE THREAD

**Issue by seorasray** [JoshuaMulliken/ha-wyzeapi#136]
Home Assistant OS 5.13
core: 2021.4.0
ha-wyzeapi: 2021.4.7

I had a couple of errors about some of my non-supproted Wyze devices, namely the "Thermostat" and what looks to be a different version of "GateWay"?

Error:
`2021-04-09 01:09:39 ERROR (MainThread) [homeassistant.components.light] Error while setting up wyzeapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 42, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.LIGHT:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'GateWay' is not a valid DeviceTypes`

Temporary Fix:

Added the following to wyzeapy/base_client DeviceTypes(Enum):
`
THERMOSTAT = "Thermostat"
GATEWAY2 = "GateWay"
`

I couldn't find the wyzeapy repo in GitHub or I would have created a Pull Request. It might be better to just check the members exist in the enum class before trying to reference them though. Something like https://stackoverflow.com/a/62065380

Thanks for the great tool, I just installed HomeAssistant today and greatly appreciate the work that you and others have done to add support for these types of products.

**Comment by JoshuaMulliken** [comment]
Thanks for the kind words @seorasray I will look get these devices included and put some logic that will prevent an exception.

**Comment by p1ironman** [comment]
@seorasray where did you add THERMOSTAT = "Thermostat" GATEWAY2 = "GateWay" exactly. After doing the update to the latest version, i have lost my ability to controll my lights and plugs.
