### ISSUE TITLE
Wyze Outdoor Plug doesn't update state on to off until after about 6 seconds after turning the plug off.

### ISSUE THREAD

**Issue by terrycarlin** [JoshuaMulliken/ha-wyzeapi#139]
When turning off the plug via Lovelace, the plug turns off immediately but it takes about 6 seconds +- to update the state to off. Can't turn the plug back on until the state has been updated.

Can duplicate by adding a Outdoor Plug to a card in Lovelace. Click on the name of the Plug to get the "more information" popup.
Notice the state entry towards the lower right of the popup. Make sure the Plug is on and the state shows on. Turn the Plug off and notice the time it takes before the state gets updated. Turn the Plug back on. Notice the state gets update immediately. Turn Plug back off then immediately try to turn the Plug back on. Nothing will happen. The state will still show on. After the state changes to off turn the switch back on and the state will update immediately.

**Comment by JoshuaMulliken** [comment]
My outdoor plug is not in yet. Will check on this once it arrives

**Comment by terrycarlin** [comment]
I can give you access to the plug if you want. It’s not controlling anything too important at this time. I gave Shaun access already.

**Comment by JoshuaMulliken** [comment]
My plug should be coming in soon and I will see if I can get this going. Won't have coding time until later this week

**Comment by dinan5** [comment]
Same issue exists with indoor plug.  I'm finding the delay to be longer than 6 seconds, maybe a minute or so.  Thanks.

**Comment by JoshuaMulliken** [comment]
Did this happen before the update to add cameras as motion sensors?

**Comment by dinan5** [comment]
Hi, I just installed the latest update and it began.  Before the change it was working perfectly.  Thanks for the quick response.

**Comment by JoshuaMulliken** [comment]
Ok, I believe that I have fixed it. Please try 2021.4.14.1

**Comment by dinan5** [comment]
My apologies but I forget how to manually pull the build.

**Comment by dinan5** [comment]
I was able to now pick up the build via HACS and its fixed.  I'm happy to be a tester if it would be helpful.  I have plugs, bulbs, and cameras.  Thank you again, great work.

**Comment by terrycarlin** [comment]
This fixed my delayed status update issue. Thanks!
