### ISSUE TITLE
[Feature Request] Add the ability to connect with 2FA enabled

### ISSUE THREAD

**Issue by viptampa** [JoshuaMulliken/ha-wyzeapi#14]
API doesn't connect / login with 2FA enabled

It has been my experience that with 2FA enabled, the api doesn't seem to be able to login.

**Comment by JoshuaMulliken** [comment]
Yea if you would like to use the api as it currently stands please disable 2FA

**Comment by JoshuaMulliken** [comment]
It doesn't appear that there isn't any interest in this feature so I will be removing this issue.
