### ISSUE TITLE
[Feature Request] Support Wyze Alarm/2nd gen sensors

### ISSUE THREAD

**Issue by joshnewman17** [JoshuaMulliken/ha-wyzeapi#140]
Are there plans to support the new sensors and alarm? I just received mine in the mail and would be happy to assist in any way that I can.

**Comment by jscherry** [comment]
The V2 sensors work with the older version of the api. I just set up the home monitoring and rebooted home assistant and all the sensors are visible and working

**Comment by frighteningkoala** [comment]
@jscherry can you confirm that the motion and door sensors actually trigger as expected?

**Comment by jscherry** [comment]
Sorry may have jumped the gun. They show all attributes but don't trigger. I'm still running version 5.14. All the V1 sensors still work properly.

**Comment by abhinav91690** [comment]
> Sorry may have jumped the gun. They show all attributes but don't trigger. I'm still running version 5.14. All the V1 sensors still work properly.

+1. V2 sensors show up but dont change values in 5.14.

**Comment by abhinav91690** [comment]
Log messages when using Home monitoring system in 2021.4.28

```

Logger: custom_components.wyzeapi.switch
Source: custom_components/wyzeapi/switch.py:48
Integration: Wyze Home Assistant Integration (documentation)
First occurred: 11:01:35 AM (2 occurrences)
Last logged: 11:01:35 AM

'Keypad' is not a valid DeviceTypes: Please report this error to https://github.com/JoshuaMulliken/ha-wyzeapi
'S1Gateway' is not a valid DeviceTypes: Please report this error to https://github.com/JoshuaMulliken/ha-wyzeapi
```

**Comment by JoshuaMulliken** [comment]
This is an upcoming feature! V2 Sensors have been ordered and are on their way!

**Comment by danielntamasi** [comment]
I just installed mine a couple of days ago, happy to be a beta tester for this functionality.

**Comment by JoshuaMulliken** [comment]
@danielntamasi awesome! I will let you know when it is ready!

**Comment by danielntamasi** [comment]
@JoshuaMulliken , I have your latest beta installed. Assuming my home is now a breeze with HA. I built a couple of automations to trigger arming based on my location and time of day. It works perfectly without a single failure after a day. 
I'll continue monitoring this. 

Looking forward to the sensor v2 integrations as well. I'm planning on implementing some automations based on open door triggers & motion sensors. 

Thank you for your development  so far  ⭐️⭐️⭐️⭐️⭐️

**Comment by JoshuaMulliken** [comment]
That is great feedback! Sensors are coming soon!

**Comment by JoshuaMulliken** [comment]
Implemented in beta. Will push to stable soon
