### ISSUE TITLE
No devices 

### ISSUE THREAD

**Issue by cmschube** [JoshuaMulliken/ha-wyzeapi#141]
Hello - have an issue where I only have one Entity in HA, but multiple on my phone.. Nothing obvious in any of the log files. 

---
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:497
Integration: Binary sensor (documentation, issues)
First occurred: April 15, 2021, 7:55:21 PM (1 occurrences)
Last logged: April 15, 2021, 7:55:21 PM

Platform wyzeapi does not generate unique IDs. ID 2CAA8E84C5FF already exists - ignoring binary_sensor.driveway_cam

---

![phone_image](https://user-images.githubusercontent.com/5130724/115044352-0cfda100-9e9b-11eb-9794-e4658ddac2ee.PNG)
![2021-04-16_9-58-57](https://user-images.githubusercontent.com/5130724/115044563-3fa79980-9e9b-11eb-9446-4d151931ebe4.png)
![2021-04-16_9-59-44](https://user-images.githubusercontent.com/5130724/115044565-40403000-9e9b-11eb-8ac7-dac5abea0ca6.png)

**Comment by shreram** [comment]
Support for sensors was removed. https://github.com/JoshuaMulliken/ha-wyzeapi/discussions/133

**Comment by JoshuaMulliken** [comment]
Only cameras can be used as motion sensors.
