### ISSUE TITLE
[Feature Request] Take a Photo?

### ISSUE THREAD

**Issue by eIiot** [JoshuaMulliken/ha-wyzeapi#143]
I understand that you're not able to integrate RSTP into this integration, but the Wyze app does have a feature to take a photo, which saves it locally. Would it be possible to create a switch for cameras that takes a photo, and saves it to homeassistant? This would really help with home security, for people like me who use HA as a security system, but Wyze as security cameras. 

LMK what you think, I would be happy to contribute some of my hardware to testing :)

**Comment by LordNex** [comment]
This would be great to help monitor the Outdoor Cams that can't do RTSP. I bought 1 before I realized that and currently is the only reason I open their crappy app.

**Comment by JoshuaMulliken** [comment]
I have access to the events, so I might be able to pull the last event video URL. Is this something that could fulfil this requirement?

**Comment by EliotHertenstein** [comment]
> 
> 
> I have access to the events, so I might be able to pull the last event video URL. Is this something that could fulfil this requirement?

This would honestly be even better! I could probably conver that to a still frame, and use that in a notification :)

**Comment by aasquith94** [comment]
Event Access would be amazing.

**Comment by yoinx** [comment]
So, digging into this a little bit... I think we could grab the video/image from an event (i actually have a commit that I need to test this with). However, taking a screenshot like the app does won't be feasible as there is no API transaction for it. It's just saving the frame from the UDP data stream (presumably RTP stream), so until we figure out how to handshake for that and connect via WebRTC.... I don't think we'll be able to snap a live photo like the app. Even if we figure it out, it would be delayed by the same amount of time that the app takes to handshake and open a video stream (not promising that this would ever be possible).

**Comment by yoinx** [comment]
Just here doing some issue housekeeping.

The original request is not possible as the app only takes a screenshot of the current frame from the video feed (which we don't have access to at this time). The request developee into events providing the image, which was also covered here https://github.com/JoshuaMulliken/ha-wyzeapi/issues/226

If this for some reason doesn't meet the request, feel free to reopen this issue. However, outside of the image from the event... We won't be able to provide any other method to screenshot the feed.
