### ISSUE TITLE
[Feature Request] Would like to have attributes like RSSI, IP, etc added to devices when available

### ISSUE THREAD

**Issue by terrycarlin** [JoshuaMulliken/ha-wyzeapi#145]
Having this information available makes it easier to track down WiFi coverage issues.

**Comment by yoinx** [comment]
@terrycarlin 

I know this is a pretty old issue...

Just curious... How often would you want those values to be updated? They require an extra poll to the device list. I just added this on a 20 minute (for now during testing) cycle to be able to pull battery status information for the outdoor cameras. I'm just curious how "live" you'd need these values to be, since they don't even update that fast in the official app.

**Comment by terrycarlin** [comment]
I think that polling the device for RSSI, IP, etc while getting the battery status would be often enough. It’s very helpful for troubleshooting issues with these WiFi devices when you can determine the WiFi signal strength. I have observed often that the WiFi signal strength will vary greatly at times probably due to interference from other 2.4mhz equipment like garage door openers, etc. From my experience, I think most of the issues that Wyze users have is directly related to WiFi signal strength so it would be nice to track it in HA.

**Comment by yoinx** [comment]
Thanks. Yeah, I think that should probably be doable. We're going to start being a bit constrained by how much were hitting the API though, do this may take some tweaking to determine the "best" frequency for updates.

**Comment by yoinx** [comment]
@terrycarlin do you know what devices have these values outside of the Wyze Cam Outdoors, Switches, and other devices that show up as switches (cameras)? I've linked a PR that adds the values for them to those on an about 20 minute update frequency.

**Comment by terrycarlin** [comment]
All my Wyze WiFi devices had RSSI, IP information when using the original WyzeApi code. It would be also nice if BSSI were available also. Then one could track a device with a low RSSI to the Access Point where it’s connected.

**Comment by yoinx** [comment]
@terrycarlin by BSSI, do you mean the SSID of the device? That's added for the switches. Unfortunately, I only have V2/V3/WCO cameras, v1 power switches, lock and keypad. So I have no idea what other devices have these. Bulbs I'm guessing?

If you're on the current beta and enable debug logging (in the readme/main page of the repo) and could share that with me, I could look at the API Response for your devices to see which other ones are reporting the info so that I can add those fields to that entity.

**Comment by terrycarlin** [comment]
The BSSI is the ip address of the wifi access point where the device is connected.
Will upgrade to current beta and send you the logs over the weekend.

Thanks

**Comment by yoinx** [comment]
Interesting. It's this in the ios app or something? I only show the device ip and the SSID of the network that it's connected to in my app on Android. I checked all my devices and don't see anything remotely showing an Access point's ip in the device info.

**Comment by yoinx** [comment]
@terrycarlin any luck with those logs or what devices are showing an ip for the access point?

**Comment by terrycarlin** [comment]
The BSSI is not included in the data. I also checked the data I retrieved from the early API an it wasn’t in that either. Don’t know why I thought it was captured before. I probably mixed it up with another unrelated project. Too bad Wyze doesn’t expose BSSI, it could be handy to see which access point is being used by a device in areas where there is a mesh network or multiple access points with he same SSID/Password. I have two access points and get that data from some non-Wyze devices. It’s interesting sometimes to see which access point the devices hook up to. It’s not always the strongest signal that wins out.  

BTW, the RSSI, IP, and SSID are missing from the Light and MeshLight devices. That data was on the early API. I think that is the only missing data now from the devices I have. Would you like me to generate another ticket? If none of the developers have access to the Light and MeshLight devices, I will share mine so they can have access to the devices.

**Comment by yoinx** [comment]
@terrycarlin 

Thanks. No idea where it would have come from. You could probably write a sensor or something that would do a traceroute to the IP of the devices and log it or something on an interval... but that's a bit outside the scope of this project. 

Sharing the devices doesn't work out as you'd expect all the time (tried this for another issue). Wyze doesn't allow the person that the device is shared with access to all the information for it. It's fairly limited tbh. If it's just the RSSI, IP, and SSID... that should be easy for me to add. It'll be a copy/paste from the other device assuming that it's using the same field names in device_params. We're sorting out some commit history stuff right now, but I should be able to get that fixed up sometime tomorrow, and hopefully, you'll see it in a beta before too soon.

**Comment by JoshuaMulliken** [comment]
@terrycarlin any problems to report? I am thinking of making it stable here soon

**Comment by terrycarlin** [comment]
Every device I have is working as advertised. Thx.

Terry

**Comment by yoinx** [comment]
Closed as resolved.
