### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by w1tw0lf** [JoshuaMulliken/ha-wyzeapi#149]
Had issues with the integration. Found that I still had the login details in configuration.yaml. Removed from the intergration as well as from hacs, as well as details in configuration.yaml. Rebooted and followed process of adding as new integration. Now keep getting, Invalid authentication. I have tested both the wyze app and website that works. Reset with new password and still the same.

Hassio: 2021.4.6
Wyze: 2021.4.28

Any suggestions? Was working perfectly before latest update.

**Comment by JoshuaMulliken** [comment]
Please be sure that you are not using a VPN I have noticed this issue where CloudFront from Amazon blocks requests that are coming from a VPN.

**Comment by JoshuaMulliken** [comment]
I am unable to replicate this issue on my instance

**Comment by w1tw0lf** [comment]
Nothing on my side changed. Only updated the integration and starting to get this error.

Looked at all logs and nothing is being blocked on my firewall.

**Comment by JoshuaMulliken** [comment]
Please enable the debug logging and provide your home assistant log. There might be something in there. If you downgrade does it start working again?

**Comment by w1tw0lf** [comment]
Tried the downgrade also no luck.

Busy reinstalling as wyzeapi doesn't show in logs even with the debug enabled.

**Comment by w1tw0lf** [comment]
Currently out of town and trying to fix via rdp to pc at home. Will be back on Saturday and continue the troubleshooting. Only have one wyze bulb connected.

**Comment by LordNex** [comment]
Yea I’m having the same trouble. It’s pulling down a list of devices and the cameras are properly acting as motion sensors. But I’m getting the same error after doing the same troubleshooting. Let me know if you want me to try something else.

Benjamin Powers

On Apr 29, 2021, at 10:03 AM, w1tw0lf ***@***.***> wrote:

﻿

Nothing on my side changed. Only updated the integration and starting to get this error.

Looked at all logs and nothing is being blocked on my firewall.

**Comment by JoshuaMulliken** [comment]
I will look into adding some additional logging to the app to help us track this issue down

**Comment by JoshuaMulliken** [comment]
If everyone can try a full restart (like bring down the Hassio instance) it might be that the dependencies are not being updated correctly. I will still look into adding more logging in the next release.

**Comment by w1tw0lf** [comment]
Checked and did try a reboot earlier... tried another one just now and for some odd reason it worked. Logged in without issues now. 

Thank you. All solved for me.

**Comment by LordNex** [comment]
> Checked and did try a reboot earlier... tried another one just now and for some odd reason it worked. Logged in without issues now. 
> 
> Thank you. All solved for me.

Not here. Still same issues. All the cams come up as valid sensors and trigger normally. But the lock still just comes up "Unavailable". I'm running inside a VMWare host if that matters. I've talked the entire instance of HA down, but i haven't rebooted the ESXi Host itself yet. Although I shouldn't need too.

**Comment by JoshuaMulliken** [comment]
It's weird that the lock is unavailable but the rest isn't. This appears to be a different issue than @w1tw0lf was having so I am closing this issue and opening a new one for your issue.
