### ISSUE TITLE
[Feature Request] Trash Mode on Door Lock

### ISSUE THREAD

**Issue by rayos006** [JoshuaMulliken/ha-wyzeapi#151]
First off love the addition of the door lock! Its been working great!

I have noticed that when you put the lock into trash mode the Door Lock in HA remains locked and no event is raised when the lock is locked again.

**To replicate:**
Put lock into Trash mode.
[Documentation](https://wyzelabs.zendesk.com/hc/en-us/articles/360042103092-Trash-Mode)

**Expected behavior:**
Lock shows unlocked while in Trash Mode and receive lock event when it gets out of Trash Mode.

**Comment by yoinx** [comment]
@rayos006 Does the official app notify you of the lock event when it exits trash mode? I have the lock, but honestly never really use trash mode... I'll have to do some testing.I also don't think that HA raises any events for the lock/unlock, at least I haven't gotten any. Do you mean like state changes that you can use in automations?

From the API standpoint, it looks like it treats trash mode separate than the lock/unlock status. I just finished writing a change to get the battery level... It provides all the other info as well in the lock settings. So I'm planning on working to implement this, so I'm just looking to clarify the expectation.

When lock mode is enabled, it should show the lock as unlocked then show it as locked once it exits trash mode?

Are you looking for a state attribute (probably boolean) to indicate trash mode as well?

**Comment by rayos006** [comment]
Hey @yoinx , 
I do receive the event within the wyze app for both unlock and the subsequent lock event while using trash mode. Yes all I'm looking for is to show the proper state changes going into and out of trash mode. Thanks so much for taking a look at this! Let me know if you need any other info.

**Comment by rayos006** [comment]
Sorry didn't see your last question. A trash mode Boolean really isn't that important to me as long as the proper state is there I'm good.

**Comment by yoinx** [comment]
@rayos006 thanks for the reply. Yeah, reporting the right state should be easy enough. Just have to check that the lock isn't in trash mode or unlocked when reporting the locked state. Hopefully I'll have something in the next few days to address it.

**Comment by yoinx** [comment]
this should, in theory, be corrected by this https://github.com/JoshuaMulliken/wyzeapy/pull/20

I believe that the lock_info endpoint properly reports the status of the lock regardless of if trashmode is enabled or not.

**Comment by yoinx** [comment]
@rayos006 the latest beta should report correctly. Any chance you could test it out and see if it's working like you'd expect?

**Comment by rayos006** [comment]
@yoinx Sorry I have been out of town. I did just update to the beta and it is now working as expected. Thank you guys for getting this working!! Now my automations will still work while in trash mode!

**Comment by yoinx** [comment]
No worries. Glad it's working as expected now.
