### ISSUE TITLE
[Bug] After updating ha-wyzeapi with HACS all of the binary_sensors for the cameras got duplicated with a _2 suffix

### ISSUE THREAD

**Issue by terrycarlin** [JoshuaMulliken/ha-wyzeapi#157]
Removed the ha-wyzeapi integration via HACS and all the devices were still in the .storage configurations. Had to manually remove them. When HA was restarted and the ha-wyzeapi integration was installed via HACS, it found all the devices and correctly named them. There might have been some other devices that ended up being duplicated but I was concentrating on the binary_sensors.

**Comment by JoshuaMulliken** [comment]
Hmm. It seems like the only way to get them to be deregistered would be to first delete the integration from the Integrations page. That would have it call the remove config entry code otherwise it would make sense that it would be left in the .storage.

@terrycarlin Do you know of anyway I can fix this particular problem?

**Comment by terrycarlin** [comment]
Ah, so I should have gone to the Integrations page to delete the config first instead of deleting the Integration using HACS? Makes sense.

I’m not sure how to fix the duplicate device part. I know that this isn’t the first integration to have the problem of duplicate devices after an update.
I will try to duplicate the process that created the duplicates. (that sentence hurt my head). If I can duplicate it, maybe I can figure out why it dups.

**Comment by JoshuaMulliken** [comment]
It's done that to me before if the old device was still in storage, but it let me edit the entity ID to something more readable. Don't know what else to do. Let me know what you find!

**Comment by JVTEAM** [comment]
Same thing happened to me.  Had to go and reassign everything.

**Comment by JoshuaMulliken** [comment]
This happened in my setup, and I am trying to find a solution but so far, no luck. If anyone finds resources on this, please link it to me.

**Comment by JoshuaMulliken** [comment]
The weirdest thing was that it only happened for two entities... I am so confused haha

**Comment by terrycarlin** [comment]
It was two devices for me also.  

If it ain't broke, take it apart and see how it works.

**Comment by iotinhome** [comment]
The following steps worked for me. 

1. Remove the integration. 
2. Goto HACS, click the 3 dots and select Reinstall (not sure if this is necessary)
2. Restart HA.
3. Received notification - new devices discovered. 

Result : Duplicates (*_2) no longer appear. All automation and cards show devices as they we before.

**Comment by LordNex** [comment]
Well changing the name and reinstalling didn’t do it, and everything else comes up the way I expect it should. But lock.side_door still shows unavailable. Adding back in ZHA with a different name and it would normally. I usually didn’t allow firmware updates except on my WOC and base. Should I see if it needs a new firmware? After TPLink and their little trick I’m very weary of IoT firmware updated breaking everything. Thanks for working on this!

LordNex

On May 11, 2021, at 9:13 AM, Joshua Mulliken ***@***.***> wrote:

﻿

Hmm, that might be part of the problem. @LordNex<https://github.com/LordNex> If you remove it from ZHA and only use it through ha-wyzeapi what happens?

**Comment by JoshuaMulliken** [comment]
@terrycarlin I have not seen this recently, I might have accidentally fixed it haha
