### ISSUE TITLE
Support turn on / off camera

### ISSUE THREAD

**Issue by praveen12bnitt** [JoshuaMulliken/ha-wyzeapi#158]
Possible to add support for turning camera on and off . It will also be nice to turn on and off motion .

https://github.com › noelportugal
noelportugal/wyze-node: An un-official API wrapper for Wyze products - GitHub

The above node module already supports both. They have already reverse engineered it, so part of the work is already done. 😀

**Comment by JoshuaMulliken** [comment]
Please update this feature has already been implemented
