### ISSUE TITLE
Entity Not Available - Switch

### ISSUE THREAD

**Issue by mgjunk** [JoshuaMulliken/ha-wyzeapi#16]
Hi there.  Thanks for doing the hard work getting the Wyze products into HA.  I was able to get 2 Wyze switches working last week no problem.  However, I needed to restart my system today for another reason and now I'm getting the dreaded "Entity Not Available" warning for the Wyze switches.  I just upgraded to the latest version and it did not fix the issue.  I also uninstalled and resinstalled the ha-wyzeapi and still got the same issue.  Any suggestions?  I'm assuming this is something on my end and not something weird like the wyze API changed...

**Comment by markrickert** [comment]
I just got an email from Wyze saying their servers were down today. Possibly related?

**Comment by JoshuaMulliken** [comment]
Can you show me your configuration.yaml? Are you installing from hacs?

**Comment by JoshuaMulliken** [comment]
@Markrickert It could be. I had to restart home assistant today to have it work again after they invalidated the tokens.

**Comment by mgjunk** [comment]
I did install from HACS.  My configuration is pretty simple (copied right from your instructions):
switch:
  - platform: wyzeapi
    username: <myemail>
    password: <mypw>

I also got the Wyze email.  Let's give it a day or so - maybe they are doing something on their end that is causing this.

**Comment by JoshuaMulliken** [comment]
@mgjunk is it working now?

**Comment by mgjunk** [comment]
Unfortunately not. 

-----
Background (in case it helps debug what happened).  Scroll down for the Error Log
-----

I have 2 Wyze plugs and a Wyze cam.  (Side note: The camera has always worked fine using rtsp and continues to work so no issues there.)

When you first released the plugin, I followed the directions and everything worked right away.  The only confusing part was that I needed to have 2 identical 'platform: wyzeapi / username/pw' sections so both the plugs would be recognized.  

I also downloaded the Wyze iOS app and was able to control the plugs through that.  

Last week I upgraded hass.io to 103.5 and I think I might have tweaked some of my configuration.yaml so I restarted HA and then the Wyze switches stopped working and haven't worked since.

I thought maybe it was the hass.io upgrade or configuration.yaml changes that caused it so I went back to an old snapshot with the previous settings but switches still not working.

Since they were having login issues, I also changed my Wyze pw on their website to try to clear any cache login issues.  

----------
LOGS from Developer Section
-----------

Log Details (WARNING)
Sun Dec 29 2019 08:50:30 GMT-0800 (Pacific Standard Time)
You are using a custom integration for wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
Connection lost. Reconnecting…


Log Details (ERROR)
Sun Dec 29 2019 08:50:31 GMT-0800 (Pacific Standard Time)
Error while setting up platform wyzeapi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/switch.py", line 45, in setup_platform
    add_entities(WyzeSwitch(switch) for switch in wyze.list_switches())
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 102, in list_switches
    for device in self.get_devices():
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 80, in get_devices
    data = do_request(url, payload, self)
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi_request.py", line 36, in do_request
    return request_helper(url, payload, api)
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi_request.py", line 25, in request_helper
    api.initialize()
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 26, in initialize
    updateConfig(self._device_id, self._access_token)
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi_config.py", line 18, in updateConfig
    config.add_section('auth')
  File "/usr/local/lib/python3.7/configparser.py", line 1205, in add_section
    super().add_section(section)
  File "/usr/local/lib/python3.7/configparser.py", line 658, in add_section
    raise DuplicateSectionError(section)
configparser.DuplicateSectionError: Section 'auth' already exists
--------------

** I noticed the "Duplicated Section"  error and thought "Maybe I need to remove that extra section for the 2nd plug" but when I did that (I only have 1 platform: wyzeapi section now) I still get the same error.


Hope that helps.  Again, thanks for all the hard work on your part!

**Comment by markrickert** [comment]
@mgjunk I'm getting this same error message this morning after upgrading from `3.0.1beta-6` to `3.0.1`.

> configparser.DuplicateSectionError: Section 'auth' already exists

I switched to the `master` branch and it seems to have resolved my issue and i can control my lights again.

It's happening on versions that i had confirmed working in the past so i'm wondering if maybe a HACS update or Home Assistant upgrade broke something?

**Comment by JoshuaMulliken** [comment]
@markrickert @mgjunk the duplicate section error should not happen on 0.3.1 it no longer includes the config parser. Sometimes you need to update in HACS twice and restart twice for it to actually install.

**Comment by mgjunk** [comment]
@JoshuaMulliken reinstalled multiple times, rebooted (and even shutdown) multiple times and same problem.  Then I did what @markrickert suggested and switched to the 'master' branch and everything worked.  Not sure what the issue is between branches

**Comment by JoshuaMulliken** [comment]
@mgjunk 0.3.1 is not substantially different from master. There must have been an issue with the update procedure. I am glad that this is resolved for you!
