### ISSUE TITLE
[Feature Request] Fire alarm / Co2 Alarm

### ISSUE THREAD

**Issue by arnaud-42** [JoshuaMulliken/ha-wyzeapi#161]
Hello,

If there is a fire or a co2 alarm my camera will send me a notification on my phone.
Is there a way to get theses alarms with your code ?

**Comment by JoshuaMulliken** [comment]
This is not a feature of the project right now. I don't think it is possible to tie into the notifications but I am happy to be proven wrong

**Comment by yoinx** [comment]
The notifications are a different API endpoint that needs to be polled. I would say that with the possibility of Wyze limiting our polling of API endpoints, this will probably have to be put on the back-burner until that is worked out... then we might be able to try and look at polling events.

**Comment by yoinx** [comment]
This may have been implemented in a similar manner to https://github.com/JoshuaMulliken/ha-wyzeapi/issues/226 in the latest beta. if you're interested in listening to the event in the screenshot there and seeing if you get an event for the fire alarm/CO2.

**Comment by yoinx** [comment]
@arnaud-42 were you ever able to test if the events functionality that was added as per the above post met your needs?

**Comment by JoeSchubert** [comment]
I'm closing this due to the lack of response from the originator. Please re-open if the above suggestions did not work.
