### ISSUE TITLE
Feature Request--Support for V1 Sensors

### ISSUE THREAD

**Issue by bjs-pdx** [JoshuaMulliken/ha-wyzeapi#164]
I am currently using an older version of your system to support my Wyze V1 sensors.  I'd like to use the new version that supports the new color bulbs and eventually the V2 sensors.  However, I won't be removing the V1s soon and the V2s are not readily available.  Would it be possible for you to add back support for the V1 sensors for now and keep it until the V2s are more widely in use?

**Comment by JoshuaMulliken** [comment]
Hey @bjs-pdx I will not be adding back v1 sensors because I do not own any that are functional and do not intend to reimplement them in my setup due to them being very inconsistent for me in the past.

You can use https://github.com/kevinvincent/ha-wyzesense if you want both. There is some information in the issues on how to make use of it still.

**Comment by mmichon** [comment]
`ha-wyzesense` requires you to pair the sensors with a bluetooth device, which unpairs them from the Wyze cloud service. I tried downgrading `ha-wyzeapi` to an older version but looks like Homeassistant has new IO rules: 
```RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/wyzeapi/smartbridge/providers/wyze/client.py, line 245: response = session.send(request, **settings)```

I can't lose support for V1 sensors, so I might just fork an old version of this repo and update it to work with recent HA versions.

**Comment by war1000** [comment]
> `ha-wyzesense` requires you to pair the sensors with a bluetooth device, which unpairs them from the Wyze cloud service. I tried downgrading `ha-wyzeapi` to an older version but looks like Homeassistant has new IO rules:
> `` RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/wyzeapi/smartbridge/providers/wyze/client.py, line 245: response = session.send(request, **settings) ``
> 
> I can't lose support for V1 sensors, so I might just fork an old version of this repo and update it to work with recent HA versions.

How did you do this? I installed an earlier version but the motion or contact sensors still don't show up.

**Comment by atjshop** [comment]
> `ha-wyzesense` requires you to pair the sensors with a bluetooth device, which unpairs them from the Wyze cloud service. I tried downgrading `ha-wyzeapi` to an older version but looks like Homeassistant has new IO rules:
> `` RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/wyzeapi/smartbridge/providers/wyze/client.py, line 245: response = session.send(request, **settings) ``
> 
> I can't lose support for V1 sensors, so I might just fork an old version of this repo and update it to work with recent HA versions.

Did you get change to make it work with v1 sensors? 
ha-wyzesense is using the same wyze bridge, I don't think it needs any other bluebooth device.

**Comment by sbritto0228** [comment]
I have Wyze Home Assistant Integration
Installed version: 83215a9
Then I installed the Wyze integration and both my cameras as well as the V1 sensors came up. Hope it helps
