### ISSUE TITLE
[Feature Request] Binary entities for thermostat state

### ISSUE THREAD

**Issue by mlhfb** [JoshuaMulliken/ha-wyzeapi#172]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Binary entities for the state of the thermostat/furnace  when calling for heating or cooling or when the fan is on

**Describe alternatives you've considered**
A single entity maybe with state text. like "off" "fan on" "fan on heating" "fan on cooling" but separate binary entities make Node Red easier. :)

**Additional context**
Thanks again for implementing the thermostat!  Knowing the state of the HVAC system to control ceiling fans, stand alone humidifiers etc. would be a big help!

**Comment by mlhfb** [comment]
@JoshuaMulliken to make a long story short about a clueless guy poking around... I managed to get shauntarves/wyze-sdk running and poked around blah blah blah... could the attribute WORKING_STATE of the thermostat be exposed to Home Assistant in your next update?  It basically returns IDLE COOLING HEATING when the system is on.  If the fan is set to on it still says IDLE but the fan mode is already exposed so thats OK.  In summary exposing attribute WORKING_STATE to Home Assistant would satisfy this feature request.  And thank you for all you do and have done to support these products!

**Comment by JoshuaMulliken** [comment]
Fixed by pull request #193

**Comment by mlhfb** [comment]
So after some more poking and figuring out that TAB is bad in python code... how to interface with the CLIMATE API of home assistant to get properties to show up for an entity, then figuring out how GIT forks and pulls work in VS CODE when your not the owner...  I managed to add this feature myself!  But the best part is Josh committed these changes before I could finish a comment on the PULL REQUEST!  Thanks again for all you do Josh!

**Comment by JoshuaMulliken** [comment]
Of course! Thank you for getting everything setup! It is a good skill to have in your back pocket!

The greatest thing about open source is making features that you want for yourself, by yourself!
