### ISSUE TITLE
[Bug] Periodically stops working

### ISSUE THREAD

**Issue by jasonmpitts** [JoshuaMulliken/ha-wyzeapi#181]
**Describe the bug**
Every few hours I loose the ability to control wyze color bulbs. either by automation or toggle switches. Restarting the Wyze Integration solves the problem.

**To Reproduce**
No steps however, I notice supervisor errors start around the time that the issues are noticed 

bug: https://github.com/home-assistant/supervisor/pull/2903

**Expected behavior**
Continious control of color bulbs connected to the network.

**System configuration**
System: Virtualbox
HA Version: Home Assistant OS 5.13
WyzeApi Version:

**Comment by JoshuaMulliken** [comment]
Please provide more logs with the debug configuration set as described in the readme. Without any more information there is no way for me to help with this issue.

**Comment by jasonmpitts** [comment]
Thank you,

I am new to this I did configure the logging when I submitted the bug report, but where do I go to retrieve the logs you need?


I also setup a REST API  call to restart the integration every 30 minutes and that has helped except for one instance yesterday where the integration failed to restart.

Thanks again,
-Jason Pitts

**Comment by JoshuaMulliken** [comment]
https://github.com/JoshuaMulliken/ha-wyzeapi#reporting-an-issue

**Comment by jasonmpitts** [comment]
Yes, I did that. Where is this log file that you want me to give you?

**Comment by JoshuaMulliken** [comment]
![image](https://user-images.githubusercontent.com/36283247/120535091-936d3400-c3b0-11eb-8f1a-267e9b048f88.png)

Please press the Load Full Home Assistant Log button and copy and paste that into a code block in response to this message.

**Comment by bjs-pdx** [comment]
I have a similar, if not the same issue.  My sensors will periodically drop off line from HA.  Would it be appropriate to drop my logs here or should I submit a separate bug report?  My sensors last reported to HA yesterday afternoon even though I know they have been activated multiple times since about midnight last night.

**Comment by bjs-pdx** [comment]
The last few days everything has been working, no disconnects.  I need to look on the Wyze forum as I seem to remember seeing something similar that was "fixed" on the servers.
