### ISSUE TITLE
Add Battery back to attributes sensors

### ISSUE THREAD

**Issue by jscherry** [JoshuaMulliken/ha-wyzeapi#185]
When I was using 5.15 I could pull the battery status from the v1 sensor attributes with a template. Is there any way to add the battery status back with the new version which still has my V1 and V2 sensors but I don't see any battery status under attributes. I love the new version is working great with the sensors and home monitoring. Thanks

**Comment by JoshuaMulliken** [comment]
@jscherry I am not going to do this anytime soon. I would accept a pul request though

**Comment by yoinx** [comment]
@jscherry there's a new beta out right now in hacs the main feature is that it supports 2fa. However, I also made the debug logs include the requests and the responses. 

I don't have any sensors, but if the battery status is included in any of the current beta's logs it would be relatively easy to add. If you could provide the logs from that beta, I'd be happy to try and implement it.

**Comment by JoshuaMulliken** [comment]
So since sensors are disabled and by all accounts will not be able to come back for some time I am going to close this issue.
