### ISSUE TITLE
All Devices Show Up as greyed out

### ISSUE THREAD

**Issue by dinan5** [JoshuaMulliken/ha-wyzeapi#195]
It looks like all releases since v0.5.12 result in all of my Wyze devices being greyed out and they cant be controlled. I dont see anything unusual in the logs.  Some of the devices are powered off intentionally but not all.  The ones that are online to Wyze should be able to be controlled by HA wyzeapi.

Thanks!

**Comment by JoshuaMulliken** [comment]
There is no information here for me to work off of. Please describe in detail the steps to replicate this.

**Comment by dinan5** [comment]
I have 4 bulbs, 2 switches, and 4 cameras.  Normal configuration is all cameras are powered off, all bulbs are powered off and only the two switches are powered on and visible to Wyze. Prior to my upgrade  everything was fine.  The devices that were powered off where greyed out, which makes sense.  The devices that weren't powered off were visible and functional from HA. Now everything is greyed out and cant be used.  please let me know what other information I can provide.  Thank you.

**Comment by JoshuaMulliken** [comment]
Have you checked the integrations page to see if they show up under the Wyze Home Assistant integration tile. I think the version you are speaking of what the one where I upgraded the system to use the new config flow method. 

This might have made your devices renamed to _2 or something similar.

**Comment by dinan5** [comment]
That looks like it - Thanks!

On Jun 13, 2021, at 7:43 PM, Joshua Mulliken ***@***.***> wrote:

﻿

Have you checked the integrations page to see if they show up under the Wyze Home Assistant integration tile. I think the version you are speaking of what the one where I upgraded the system to use the new config flow method.

This might have made your devices renamed to _2 or something similar.

**Comment by JoshuaMulliken** [comment]
Great! I will pin this so that if anyone else has this problem they will see it.

**Comment by dinan5** [comment]
Thank you again.

**Comment by mmatus1112** [comment]
My wyze plugs greyed out today. 
![image](https://user-images.githubusercontent.com/72715377/129637678-1623db18-d79d-43a0-bf6d-fb3362944fe9.png)
