### ISSUE TITLE
[Bug] "Request is forbidden due to login anomaly"

### ISSUE THREAD

**Issue by jayburkard** [JoshuaMulliken/ha-wyzeapi#198]
All of my Wyze lights greyed out last night... I removed/reinstalled the add on, went to an older version, changed my password, all to no avail. 2FA isn't enabled. Any ideas? Screenshot shows log information. I can login via wyze website and via the app without an issue.

![image](https://user-images.githubusercontent.com/37115112/121977922-0da89b80-cd55-11eb-8c27-3e7b7595a51f.png)

**Comment by JoshuaMulliken** [comment]
Do you use a VPN or is your IP on a blacklist?

**Comment by jayburkard** [comment]
> Do you use a VPN or is your IP on a blacklist?

Ahhhhh yep, pfsense + protonVPN. My PC that logged in is also behind same VPN but ill try excluding my Ubuntu VM from passing through VPN this evening. Wasn't an issue until yesterday but maybe IP just got added to blacklist.

**Comment by jayburkard** [comment]
You are the man! Set the VM that hosts home assistant to use regular gateway instead of protonvpn, good to go now. Thanks for the help, sorry for the bug report!

**Comment by JoshuaMulliken** [comment]
No worries! That's what they are for!
