### ISSUE TITLE
[Bug] <short description of issue>

### ISSUE THREAD

**Issue by fun4stuff** [JoshuaMulliken/ha-wyzeapi#210]
**Describe the bug**
Failed to set up wyze on reboot after upgrade. 

**To Reproduce**
Update wyze then restart ha server

**Expected behavior**

**System configuration**
System: 
HA Version: 
WyzeApi Version: 

**configuration.yaml**

```yaml
<YOUR CONFIG HERE>
```

**home-assistant.log**

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/wyzeapi/__init__.py", line 85, in async_setup_entry
    mac_addresses = await client.unique_device_ids
  File "/usr/local/lib/python3.8/site-packages/wyzeapy/__init__.py", line 68, in unique_device_ids
    devices = await self._service.get_object_list()
  File "/usr/local/lib/python3.8/site-packages/wyzeapy/services/base_service.py", line 92, in get_object_list
    check_for_errors_standard(response_json)
  File "/usr/local/lib/python3.8/site-packages/wyzeapy/utils.py", line 22, in check_for_errors_standard
    raise ParameterError(response_json)
wyzeapy.exceptions.ParameterError: {'ts': 1625429458018, 'code': '1001', 'msg': 'ParameterError', 'data': {}}

Ensure that your logger is set up by adding this to your configuration.yaml
logger:
  default: warning
  logs:
    custom_components.wyzeapi: debug

For additional information see the readme: https://github.com/JoshuaMulliken/ha-wyzeapi#reporting-an-issue
-->

```
<PUT YOUR LOG HERE>
```

**Comment by JoshuaMulliken** [comment]
Please finish filling the template

**Comment by JoshuaMulliken** [comment]
@fun4stuff I will be closing this as there is no information, and it seems like you put very little effort into providing enough. Information

**Comment by fun4stuff** [comment]
The prior update broke the integration for home assistant...

**Comment by JoshuaMulliken** [comment]
If you want help you need to help yourself by filling out the template I provided. You didn't even create a title.
