### ISSUE TITLE
[Bug] Upgrading Wyze Integration broke all devices

### ISSUE THREAD

**Issue by frighteningkoala** [JoshuaMulliken/ha-wyzeapi#211]
**Describe the bug**
I just upgraded your awesome HA integration from ~2021.6.4 to 2021.7.8 then 2021.7.9. In both of these versions, none of my wyze devices are showing up.

I've tried deleting and reconfiguring the integration and that didn't seem to help.

I've also rebooted several times.

**To Reproduce**

1. Go to overview after performing this update, all devices are grayed out.
2. If you remove the integration and add it again, the integration appears to configure alright, but no devices are detected.

**Expected behavior**
* I expect my devices to show up.

**System configuration**
System: Docker
HA Version: 2021.4.6
WyzeApi Version: 2021.7.9

**configuration.yaml**
<no wyze config in here for me, that wasn't needed previously and still doesn't seem to be needed according to the readme>

**home-assistant.log**
```
2021-07-05 22:03:51 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Wyze for wyzeapi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/wyzeapi/__init__.py", line 84, in async_setup_entry
    hass.create_task(hass.config_entries.async_forward_entry_setup(config_entry, platform))
AttributeError: 'HomeAssistant' object has no attribute 'create_task'
```

**Comment by JoshuaMulliken** [comment]
What version of Home Assistant are you using?

Thanks,

Josh Mulliken

On July 5, 2021, GitHub ***@***.***> wrote:
> Describe the bug
>  I just upgraded your awesome HA integration from ~2021.6.4 to
> 2021.7.8 then 2021.7.9. In both of these versions, none of my wyze
> devices are showing up.
>
> I've tried deleting and reconfiguring the integration and that didn't
> seem to help.
>
> I've also rebooted several times.
>
> To Reproduce
>  Steps to reproduce the behavior:
>
> 1. Go to overview after performing this update, all devices are
>    grayed out.
> 2. If you remove the integration and add it again, the integration
>    appears to configure alright, but no devices are detected.
>
> Expected behavior
>
>  *  I expect my devices to show up.
>
> System configuration
>  System: Docker
>  HA Version: 2021.4.6
>  WyzeApi Version: 2021.7.9
>
> configuration.yaml
>  <no wyze config in here for me, that wasn't needed previously and
> still doesn't seem to be needed according to the readme>
>
> home-assistant.log
>
> 2021-07-05 22:03:51 ERROR (MainThread) [homeassistant.config_entries]
> Error setting up entry Wyze for wyzeapi Traceback (most recent call
> last): File "/usr/src/homeassistant/homeassistant/config_entries.py",
> line 249, in async_setup result = await
> component.async_setup_entry(hass, self) # type: ignore File
> "/config/custom_components/wyzeapi/__init__.py", line 84, in
> async_setup_entry
> hass.create_task(hass.config_entries.async_forward_entry_setup(config_entry,
> platform)) AttributeError: 'HomeAssistant' object has no attribute
> 'create_task'

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/JoshuaMulliken/ha-wyzeapi/issues/211>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AIU2G35OL4QIALSCJHQ4VXDTWIOI7ANCNFSM473LELEA>.

**Comment by frighteningkoala** [comment]
> What version of Home Assistant are you using?

2021.4.6.

**Comment by JoshuaMulliken** [comment]
Hmm I am unable to replicate. The log says that it is missing a function on the HomeAssistant object. This leads me to believe that something is wrong with your installation because the bass.create_task function exists for me.

**Comment by frighteningkoala** [comment]
What version of HomeAssistant are you on? I'll look into upgrading to see if that helps.

**Comment by frighteningkoala** [comment]
I can confirm this issue is resolved on 2021.6.6. Thanks for the suggestion, and for the awesome integration.

**Comment by JoshuaMulliken** [comment]
Of course! Thanks for the submission let me know if you run into any bugs

**Comment by musicjeremy** [comment]
Hello! I had the same issue which was also resolved by upgrading HA (in this case I went to :latest).
