### ISSUE TITLE
Fails to startup: wyze_config.ini missing?

### ISSUE THREAD

**Issue by roger-** [JoshuaMulliken/ha-wyzeapi#217]
HA gives an integration failed to start error and the following traceback:

```
Traceback (most recent call last):
  File "/home/user/Software/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/user/.homeassistant/custom_components/wyzeapi/__init__.py", line 103, in async_setup_entry
    uid = await hass.async_add_executor_job(get_uid)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.homeassistant/custom_components/wyzeapi/__init__.py", line 98, in get_uid
    with open('wyze_config.ini', 'w') as configfile:
PermissionError: [Errno 13] Permission denied: 'wyze_config.ini'
```

I tried creating a wyze_config.ini file (it was missing), but I'm not sure what path it's looking in.

**Comment by JoshuaMulliken** [comment]
So the container needs to be able to write to the root of the Home Assistant config path (same directory as configuration.yml)

**Comment by roger-** [comment]
I'm using a Python installation of HA (no container) with ha-wyzeapi installed via HACS.

**Comment by JoshuaMulliken** [comment]
Ok well ensure that the folder that contains configuration.yml has the right permissions set so that ha can write the file. It should create it on startup.

**Comment by pailloM** [comment]
Running HA in a python venv on Debian, it is trying to write the file in the root directory / 
Providing a full path for the file solved the issue for me.

In __init__.py and switch.py, I have replaced the line:
`with open('wyze_config.ini', 'w') as configfile:`

with:
```
import os

with open(f'{os.path.dirname(os.path.abspath(__file__))}{os.sep}wyze_config.ini', 'w') as configfile:
```
All working as expected like this, the file is being created in the wyzeapi custom_components folder. No errors on startup.

**Comment by roger-** [comment]
I was able to fix it along the lines of what @pailloM mentioned by hard coding the ini path.

**Comment by JoshuaMulliken** [comment]
So this is an issue when not running supervised or through a container?

**Comment by roger-** [comment]
Yes, I think so.

**Comment by pailloM** [comment]
I think it is an issue when home-assistant is not allowed to write a file in the root folder. Mainly core installation.
I would suggest to place the file in the wyzeapi custom_components folder or in the home-assistant config directory.

**Comment by roger-** [comment]
Still having issues:

```
  File "/home/user/.homeassistant/custom_components/wyzeapi/__init__.py", line 101, in get_uid
    with open(config_path, 'w') as configfile:
PermissionError: [Errno 13] Permission denied: '//wyze_config.ini'
```

Tried reinstalling the integration but still getting error.

**Comment by krhainos** [comment]
Can confirm __init__.py and switch.py require modifying as mentioned by @pailloM before this integration successfully starts.

(None of my devices or entities are showing up as available, but that's likely a separate issue.)

**Comment by pailloM** [comment]
os.getcwd() returns root also. In a virtual environment, it is not accessible by home-assistant therefore the error is still present. This is why I suggested to use the directory of the current python module.
It would be preferable to store the path in a variable in the __init__.py and have the modules that need access to the config file to import that variable from __init__.py

**Comment by JoshuaMulliken** [comment]
This has made it into a release! Thank you @leoledmag for the help!
