### ISSUE TITLE
[Feature Request] Wyze Floor Lamp

### ISSUE THREAD

**Issue by rjtort** [JoshuaMulliken/ha-wyzeapi#218]
Possible to get the new Wyze Floor Lamp added? https://wyze.com/wyze-floor-lamp.html
Hoping it's similar enough to the bulbs to get it added for similar functionality.

**Comment by BoredMind** [comment]
The floor lamp works off of Bluetooth and doesn't connect to the internet.

**Comment by rjtort** [comment]
Did not realize that. Thought it was only the control dial that was bluetooth. Never mind! Thanks for the quick reply though.
