### ISSUE TITLE
[Bug] Lock Status Fails to Update after Auto Lock

### ISSUE THREAD

**Issue by aleck011mi** [JoshuaMulliken/ha-wyzeapi#219]
**Describe the bug**
In an update that occurred in the last couple weeks, when I unlock my Wyze lock with Home Assistant and then lock it from the inside manually, the Wyze app shows the door is locked but Home Assistant never receives the locked status.

**To Reproduce**

1. Go to outside of door which is locked.
2. Unlock door with Home Assistant (I use the quick launch buttons in the Pixel Power Menu)
3. Enter door once manually locked.
4. Manually lock Wyze lock.

**Expected behavior**
Prior to an update that came out a couple weeks ago, the lock status would update regardless of manual or automated lock/unlock.

**System configuration**
System: Docker
HA Version: Latest, 2021.7.2
WyzeApi Version: Latest, 2021.7.10

**configuration.yaml**

```yaml
<YOUR CONFIG HERE>
```

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```

**Comment by JoshuaMulliken** [comment]
I can reproduce. I will check this out

**Comment by JoshuaMulliken** [comment]
@aleck011mi in the future please fill all the required fields. I will begin to close issues that do not include a title or are missing logs
