### ISSUE TITLE
[Bug] HA on docker, HACS Wyze install can't complete

### ISSUE THREAD

**Issue by rileytb** [JoshuaMulliken/ha-wyzeapi#220]
**Description**
Can't complete setup of Wyze HACS integration. Fails after setup.

**To Reproduce**

1. Install Wyze integration from HACS
2. Restart HA
3. Install integration, input username/password

**Expected behavior**
Integration to install, no errors in logs, and find Wyze devices from account.

**System configuration**
System: Docker
HA Version: 2021.4.6
WyzeApi Version: 2021.7.10

**configuration.yaml**
not doing any of this through the config

**home-assistant.log**

```
Logger: homeassistant.config_entries
Source: custom_components/wyzeapi/__init__.py:84
First occurred: 9:27:48 PM (1 occurrences)
Last logged: 9:27:48 PM

Error setting up entry Wyze for wyzeapi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/wyzeapi/__init__.py", line 84, in async_setup_entry
    hass.create_task(hass.config_entries.async_forward_entry_setup(config_entry, platform))
AttributeError: 'HomeAssistant' object has no attribute 'create_task'
```

**Comment by JoshuaMulliken** [comment]
Please update your HA

**Comment by rileytb** [comment]
Ah, that solved it, thanks!
