### ISSUE TITLE
INtegration Does not Appear After HACS install

### ISSUE THREAD

**Issue by johnjoemorgan** [JoshuaMulliken/ha-wyzeapi#225]
**Describe the bug**
After install in HACS and restart there is no Wyze integration to install

Not a lot more I can add.....

**Comment by partsguymatt** [comment]
It is a custom repository.

https://hacs.xyz/docs/faq/custom_repositories/

**Comment by partsguymatt** [comment]
Seeing the same, fresh install of Home Assistant and HACS, added this custom repository. Rebooted, and no Wyze integration in config>integrations>add integration

**Comment by JoshuaMulliken** [comment]
> ~Seeing the same, fresh install of Home Assistant and HACS, added this custom repository. Rebooted, and no Wyze integration in config>integrations>add integration~
> 
> Update - had to hard refresh the browser while on the integration page.

@johnjoemorgan does this fix your issue?

**Comment by johnjoemorgan** [comment]
@JoshuaMulliken Yep - I had restarted but not hard refreshed (Ctrl&F5).  Schoolboy error :-)  - All fixed
