### ISSUE TITLE
[Feature Request] Wyze Notifications

### ISSUE THREAD

**Issue by eIiot** [JoshuaMulliken/ha-wyzeapi#226]
**Is your feature request related to a problem? Please describe.**
Wyze notifications are Garbage.

**Describe the solution you'd like**
Would it or possible to send camera notifications as events to HA? This way we could manage notifications through automations or NR, and save a lot of hassle. Also would allow families to have central notifications.

**Describe alternatives you've considered**
Tasker android server, that intercepts notifications and send them to HA

**Comment by yoinx** [comment]
> **Is your feature request related to a problem? Please describe.** Wyze notifications are Garbage.
> 
> **Describe the solution you'd like** Would it or possible to send camera notifications as events to HA? This way we could manage notifications through automations or NR, and save a lot of hassle. Also would allow families to have central notifications.
> 
> **Describe alternatives you've considered** Tasker android server, that intercepts notifications and send them to HA

When you say "send them to HA"... what are you sending them to HA as? I'm looking at ways of integrating this... But I'm not entirely sure how they should go to HA, as it's not a feature that I would likely use.

**Comment by eIiot** [comment]
Ideally, events. They're easy to listen to with node red :)

**Comment by yoinx** [comment]
> Ideally, events. They're easy to listen to with node red :)

I hate to sound like a newb, but do you have an example of how you're doing that? I don't see a free form event type in the docs so far for HA.

**Comment by eIiot** [comment]
Yep, I'd take a look at this:
https://developers.home-assistant.io/docs/dev_101_events/

You can use JSON and it can be parsed either in node red or automations.

**Comment by yoinx** [comment]
> Yep, I'd take a look at this: https://developers.home-assistant.io/docs/dev_101_events/
> 
> You can use JSON and it can be parsed either in node red or automations.

Thanks. Yeah, I think that's probably how I'll go about it

**Comment by yoinx** [comment]
I've just pushed a PR for this. Would a data structure like described in the PR work for what you're requesting?

**Comment by eIiot** [comment]
This is great! Being able to trigger automations & notifications from HA is amazing :)

**Comment by yoinx** [comment]
Yeah, as long as wyzeapy updates that correctly (didn't test it much) it should work fine. If not, I'll have to do more work on the backend. Just wanted to make sure I was in the right track for the request.

**Comment by yoinx** [comment]
so, it wasn't originally working in my commit... But I think I've got it now. This is what's in one of those commits there, it will only fire for new events once the integration is running (it doesn't get old ones before that) and grabs the last one every 30 seconds or so when the switch updates... hopefully this is what you envisioned? I don't have any of the pro features to debug the ai_tag_list or tag_list fields.

![image](https://user-images.githubusercontent.com/1645503/140592806-5567f10b-2f7d-4e78-9ea4-2fe490e72007.png)

**Comment by eIiot** [comment]
Oh awesome, the video urls are included and everything!

**Comment by yoinx** [comment]
> Oh awesome, the video urls are included and everything!

Looks like Josh put this out as one of the feature in the beta 2021.11.1b1

If you want to test it out and see if it's what you were looking for.

**Comment by eIiot** [comment]
Cool!

I wonder if this could be used for updated motion sensors? Since it's already sending the service calls, we could always update the sensors when a new notification is sent...

I don't know how to implement that though...

**Comment by yoinx** [comment]
> Cool!
> 
> I wonder if this could be used for updated motion sensors? Since it's already sending the service calls, we could always update the sensors when a new notification is sent...
> 
> I don't know how to implement that though...

This had been discussed, but since it's delayed by up to 30 seconds minimum, it probably isn't worthwhile for people who wanted sensors. The sensors from the cameras were intended to work the same as the actual sensors when they were implemented, where's they would give near instant feedback. It would probably confuse people and lead to an increase of issues being opened to change that now.

**Comment by yoinx** [comment]
@eIiot were you able to test out the beta at all? I'm curious how it worked for you?

**Comment by eIiot** [comment]
> @eIiot were you able to test out the beta at all? I'm curious how it worked for you?

Yep, it's working good, except for video urls not really working. They always appear as null.

Working good for my use case overall, though!

**Comment by yoinx** [comment]
> except for video urls not really working. They always appear as null.

Weird. Is that from an automation, or from listening to the event in developer tools? The screenshot that I posted above was from developer tools within home assistant's web interface which *seemed* to get it fine. However, in the data from Wyze, there's 2 possible spots for the links, so I'm wondering if maybe we need to use the other spot.

Might you be comfortable manually editing a python file to test something? I'm thinking that if you edit this line: https://github.com/JoshuaMulliken/ha-wyzeapi/blob/923707c37e38dc63ddb2b74bf194075e078cc47f/custom_components/wyzeapi/switch.py#L262

from
"for resource in event.file_list:"
to
"for resource in event.event_resources"

it might give you the link correctly.

**Comment by eIiot** [comment]
Sure I'll give that a try soon. And yes I was listening from dev tools

**Comment by eIiot** [comment]
I don't think it worked, I'm not receiving any events now :/

**Comment by yoinx** [comment]
Weird. During my testing the urls showed in both locations, I'm unsure if maybe a camera setting makes it so one isn't available or something though.

Which model(s) of camera?

**Comment by eIiot** [comment]
V3, although it's running the RTSP firmware. Might be an issue with that?

**Comment by hickerad** [comment]
Just to add to this one. I am using a mix of the v3, v2, outdoor and pan cameras running the standard firmware from Wyze and I am seeing the same issue as @eIiot. The URL for the video stream is null.

**Comment by yoinx** [comment]
I'll have to do more testing it looks like. I use v2, v3, campan and wyze cam outdoors... And they all seemed to be there for me, though I admittedly only did a little testing as my wife doesn't really like me playing with "her" cameras.

When you guys say "null" though. Do you mean that it shows as 

"event_video": ""
"event_video": "null"
"event_video":

Or some other output there? Just trying to wrap my head around what's going on. I *doubt* the rtsp firmware should make any difference, same with a cam plus subscription (if either of you have one). 

If you set wyzeapy to debug for logging (per the GitHub readme), you'll get a bunch of output. The response from the sections where the request url is https://api.wyzecam.com/app/v2/device/get_event_list would be super helpful (feel free to sanitize the urls, it's something we should probably sanitize anyway thinking about it).

**Comment by eIiot** [comment]
I think it was showing as "event_video": "null". However, I'm not experiencing the issue now.

I think it might be an issue on wyze's end. Sometimes, I don't get pictures in notifications just because of some issue with the cameras.

**Comment by yoinx** [comment]
> I think it was showing as "event_video": "null". However, I'm not experiencing the issue now.
> 
> I think it might be an issue on wyze's end. Sometimes, I don't get pictures in notifications just because of some issue with the cameras.

Not experiencing it because the change I asked you to make broke it? Or because it cleared up?

If it's actually got the text "null" then that's something coming from wyze in that field. If it was something happening programmatically, it would just be blank as I'm not substituting any text into that value if the url is empty.

**Comment by eIiot** [comment]
Yep, it looks to be a Wyze issue.

I'm not experiencing it anymore, even after reinstalling. So no, it just was an issue on Wyze's end from the beginning.

**Comment by yoinx** [comment]
> Yep, it looks to be a Wyze issue.
> 
> I'm not experiencing it anymore, even after reinstalling. So no, it just was an issue on Wyze's end from the beginning.

Cool, so you're getting the image and video links now?

**Comment by eIiot** [comment]
> Cool, so you're getting the image and video links now?

Yep!

**Comment by yoinx** [comment]
Any chance that you're getting anything in either tag list? I don't pay for that feature.

**Comment by eIiot** [comment]
Not currently, no.

**Comment by eIiot** [comment]
Just tested again, for some reason I am now.

I think 99% of these issues are just Wyze being weird with their notifications. I have the same issues with notifications on android all the time (no picture, no tag, etc)

**Comment by eIiot** [comment]
![Inkedfirefox_K3MZML7hY4](https://user-images.githubusercontent.com/39346975/141375864-664bd7d4-9ead-49d4-8340-1648a912b8f2.jpg)
Just recieved this. 

Then for reference, like 5 seconds later:

![image](https://user-images.githubusercontent.com/39346975/141376052-65a5ee82-71e8-4f35-88bc-6f539e981380.png)

**Comment by yoinx** [comment]
Yeah, I don't think there's much I can do about it if they're sending "null" there. Looking at codes that were deciphered "elsewhere" it looks like 104 in the tags is "package"as the tag. So I guess I'll have to decipher those before sending them in the event.

Thanks!

**Comment by nijhawank** [comment]
@yoinx @JoshuaMulliken I see that we have now enabled events for wyze cameras. Going by the above discussion and some review of the code, it seems it is still polling the Wyze Servers for any change in state but it seems we are probably doing a group poll and/or doing it every 30 seconds. 
Are we sure that Wyze is ok with this i.e. 30 second polls, and won't block like last time when Joshua had to remove the cameras as motion sensors feature. How frequent the polling was then?

**Comment by eIiot** [comment]
These seem to be working great, so I'll close the FR. Thanks again @yoinx!

**Comment by dnestico** [comment]
Just wondering, how do I access the notifications or was this removed / not added? Thanks.
