### ISSUE TITLE
[Feature Request] Additional code clarity and comments

### ISSUE THREAD

**Issue by markrickert** [JoshuaMulliken/ha-wyzeapi#23]
It appears that there's a unique identifier hardcoded into the `WyzeApi` class that's being included in every payload that this code sends from every instance. Shouldn't something called `device_id` be something the user should configure?

https://github.com/JoshuaMulliken/ha-wyzeapi/blob/master/custom_components/wyzeapi/wyzeapi/wyzeapi.py#L17

<img width="786" alt="Screen Shot 2020-01-01 at 2 16 32 PM" src="https://user-images.githubusercontent.com/139261/71646209-95096880-2ca1-11ea-9163-a4c651e57593.png">

And then it's included in the payload for each API call:

https://github.com/JoshuaMulliken/ha-wyzeapi/blob/master/custom_components/wyzeapi/wyzeapi/wyzeapi.py#L37

<img width="826" alt="Screen Shot 2020-01-01 at 2 17 02 PM" src="https://user-images.githubusercontent.com/139261/71646219-cbdf7e80-2ca1-11ea-87d8-2c4e0fecd32b.png">

---

Additionally... i realize that there are some other parameters that you're sending that are basically "spoofing" the app, correct? What are some of these values? Perhaps documenting inline that they're "magic numbers" required to interact with the api?

I'm wondering if i sniffed my app network requests if I'd have the same values... or the same `device_id` that's being sent? 🤔

```
"sc":"9f275790cab94a72bd206c8876429f3c",
"ts":"1575953834054",
"sv":"9d74946e652647e9b6c9d59326aef104",
```

Thanks for the great work on this so far... I'm digging into the source code to see if i might be able to help in the future! I'm not a python guy, but this stuff piques my interest!

**Comment by JoshuaMulliken** [comment]
The device_id is not from my phone but I found some guids from another git repo that worked. It doesn't appear like it has to be from a specific phone for it to work. But it does need to be one that it is already registered. Basically this is a magic number. The others are also magic and I don't know what they do.

**Comment by aeckard87** [comment]
@JoshuaMulliken I think I know where you grabbed it from, before I found your awesome work, I also stumbled on someones work to integrate with wyze cameras but the endpoints are pre /v2/ - the only thing it provided from their docs, [here](https://github.com/nblavoie/wyzecam-api)

is that **ts** stands for current time in milliseconds.

**Comment by JoshuaMulliken** [comment]
@aeckard87 Thank you for the information! Maybe we can start filling in some of these parameters with real data lol. Maybe a request builder would be a useful functionality for readability.

**Comment by jfarmer08** [comment]
I have started a new project for Documents. If anyone wants help.
https://github.com/jfarmer08/Wyzeapi_Documents

**Comment by JoshuaMulliken** [comment]
@jfarmer08 maybe we can make those part of a wiki on this project for visability

**Comment by JoshuaMulliken** [comment]
@jfarmer08 I added your awesome docs to the wiki. I did some grammar checking and formatting but otherwise, it is exactly the same.

**Comment by JoshuaMulliken** [comment]
@all I think this issue is resolved by the wiki
