### ISSUE TITLE
[Feature Request] Sound sensor

### ISSUE THREAD

**Issue by SeeDborg** [JoshuaMulliken/ha-wyzeapi#234]
I think the Wyze Can pam Cameras have sound sensors, would it be possible to enable it ?

**Comment by yoinx** [comment]
@SeeDborg I have the campan. I see it has sound detection sensitivity.... Is this what you mean, or are you talking about the smoke/CO2 alarm detection? Is it different than the v2/v3 sound detection?

**Comment by SeeDborg** [comment]
YEs I'm talking about the sound detection. I don't know if it's different than the v2/v3

**Comment by yoinx** [comment]
So I think that this is likely sent as an event, not as data field from the camera itself. This may have to go into a "TODO" que pending whether or not we can poll the events with the API limits.

**Comment by yoinx** [comment]
This may have been implemented by the same process that was used for https://github.com/JoshuaMulliken/ha-wyzeapi/issues/226 . I would assume that wyze send this as an event with a sound tag or something.... I don't use the sound sensor personally, but you could listen to the event like in the screenshot posted there with the latest beta ... And see if you get the events for the sound sensor.

**Comment by JoeSchubert** [comment]
I believe this was implemented per my last comments over a year ago. 

Closing as stale, please reopen if it was not.
