### ISSUE TITLE
[Bug] Corrupt Repo on Install.

### ISSUE THREAD

**Issue by EmmanuelZapata** [JoshuaMulliken/ha-wyzeapi#235]
**Corrupt Repo during install**
Try to install repo and get that it is corrupt.
IssueType.CORRUPT_REPOSITORY - ContextType.STORE 

**To Reproduce**

1. Go to add-on store 
2. Click on three dots top right then repositories 
3. add the repo https://github.com/JoshuaMulliken/ha-wyzeapi
4. See error: corrupt repo

**Expected behavior**
I expected to see the repo added.

**System configuration**
System: Operating System Home Assistant OS 6.2 (in a VM)
HA Version: core-2021.8.8, supervisor-2021.06.8
WyzeApi Version: repo 

**home-assistant.log**

```
21-08-23 11:24:08 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/JoshuaMulliken/ha-wyzeapi repository
21-08-23 11:24:09 ERROR (MainThread) [supervisor.store] https://github.com/JoshuaMulliken/ha-wyzeapi is not a valid add-on repository
21-08-23 11:24:09 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / 4824be1f
21-08-23 11:24:09 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / 4824be1f
21-08-23 11:24:09 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/4824be1f
21-08-23 11:24:10 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 0 new - 0 remove
21-08-23 11:24:10 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: 4824be1f
21-08-23 11:24:10 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/JoshuaMulliken/ha-wyzeapi
```

**Comment by JoshuaMulliken** [comment]
This must be installed through [HACS](https://hacs.xyz) It is actually now a part of the standard repos there so once you install it you can directly install this from there
