### ISSUE TITLE
[Bug] <Error on startup/login, no attribute "create_task">

### ISSUE THREAD

**Issue by jayburkard** [JoshuaMulliken/ha-wyzeapi#241]
**Describe the bug**
Updated to latest version, deleted integration and reinstalled from HACS. 

**To Reproduce**

1. Set up integration, log in
2. See error

**Expected behavior**

Wyzeapi to login as on older versions.

**System configuration**
## System Health

version | core-2021.5.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.11.0-25-generic
arch | x86_64
timezone | UTC

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4957
Installed Version | 1.15.1
Stage | running
Available Repositories | 876
Installed Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | September 6, 2021, 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 21.04
-- | --
update_channel | stable
supervisor_version | supervisor-2021.08.1
docker_version | 20.10.7
disk_total | 1006.9 GB
disk_used | 24.1 GB
healthy | failed to load: Unhealthy
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.1), Mosquitto broker (6.0.1), Frigate NVR (1.13), ESPHome (1.18.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 1
views | 4
mode | storage

</details>

WyzeApi Version: 

**home-assistant.log**

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/wyzeapi/__init__.py:85
Integration: Wyze Home Assistant Integration (documentation, issues)
First occurred: 9:43:13 PM (1 occurrences)
Last logged: 9:43:13 PM

Error setting up entry Wyze for wyzeapi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/wyzeapi/__init__.py", line 85, in async_setup_entry
    hass.create_task(hass.config_entries.async_forward_entry_setup(config_entry, platform))
AttributeError: 'HomeAssistant' object has no attribute 'create_task'

```

**Comment by JoshuaMulliken** [comment]
@jayburkard we fixed your issue on IRC right? Just the update to HA core?

**Comment by jayburkard** [comment]
> @jayburkard we fixed your issue on IRC right? Just the update to HA core?

Yessir! That fixed it. Greatly appreciate the help.
