### ISSUE TITLE
[Bug] Remove unavailable/disabled entities

### ISSUE THREAD

**Issue by JoshuaMulliken** [JoshuaMulliken/ha-wyzeapi#255]
**Describe the bug**

After the update to remove sensors that were hammering the Wyze servers there are a large number of unavailable entities that cannot be removed from Home Assistant.

**To Reproduce**

1. Upgrade from a version that supports motion sensors/contact sensors
2. Open the "Integrations" page under "Configuration"
3. Click on the "entities" hyperlink under the Wyze integration
4. See that many unavailable entities are listed

**Expected behavior**

Entities that are no longer supported should be cleaned up on a reboot.

**System configuration**
System: Docker
HA Version: core-2021.9.7
WyzeApi Version: 2021.9.3

**Comment by yoinx** [comment]
This bug may make more sense as "remove platforms that are not part of the integration".

I'd be a little upset if the integration removed something just because I disable it, or it goes offline for a bit.

**Comment by JoshuaMulliken** [comment]
Yeah the primary issue is we disabled the binary sensors but the entities are still there

**Comment by yoinx** [comment]
I think it would make more sense then to do a "cleanup loop" to make sure the entities belong to an included platform and just remove them if they don't.

**Comment by yoinx** [comment]
I only listed the models that I currently own... we'll probably need to poll the userbase to ensure that we get all the models covered using something like this... 

But what do you think about handling this bug something like this? https://github.com/yoinx/ha-wyzeapi/commits/bug_255-remove_unsupported_devices

**Comment by JoshuaMulliken** [comment]
@yoinx this was fixed in a previous release right?

**Comment by yoinx** [comment]
@JoshuaMulliken it was in a testing set of features that I guess got merged. But it introduced a bug as reported here https://github.com/JoshuaMulliken/ha-wyzeapi/issues/144#issuecomment-986412679

**Comment by yoinx** [comment]
It was added into develop in this commit. https://github.com/JoshuaMulliken/ha-wyzeapi/commit/923707c37e38dc63ddb2b74bf194075e078cc47f

But I don't even see that function in master... So not sure how they're getting the issue in the current release.

**Comment by JoshuaMulliken** [comment]
Weird. Maybe they had installed the beta?

**Comment by yoinx** [comment]
@JoshuaMulliken did we still want to try and pursue this, or just leave it to the end-user to delete/cleanup dead entities?

**Comment by JoshuaMulliken** [comment]
I am pretty sure that a fix for this is in prerelease. When that goes to stable (hopefully today) this should get closed

**Comment by yoinx** [comment]
Oh? I thought the only thing related to removing anything there concerned properly removing updaters from the wyzeapy update manager.

**Comment by JoeSchubert** [comment]
@JoshuaMulliken I've been gone for awhile... Is this still an issue or can it be closed?

**Comment by JoshuaMulliken** [comment]
Yeah, I think we can close it!
