### ISSUE TITLE
Wyzeapi configuration changed in v0.4.0

### ISSUE THREAD

**Issue by kburnes** [JoshuaMulliken/ha-wyzeapi#26]
Joshua - The beta fix yesterday worked - but today the v0.4.0 fails with:

Log Details (ERROR)
Thu Jan 02 2020 11:51:05 GMT-0500 (Eastern Standard Time)
Invalid config for [light.wyzeapi]: [username] is an invalid option for [light.wyzeapi]. Check: light.wyzeapi->username. (See /config/light.yaml, line 0). Please check the docs at https://home-assistant.io/integrations/wyzeapi/

also the docs link listed in the error message comes back with a 404 error.

**Comment by JoshuaMulliken** [comment]
Please check the read me. V0.4.0 is a **breaking change** please follow the information here: https://github.com/JoshuaMulliken/ha-wyzeapi

**Comment by kburnes** [comment]
I'm embarrassed.  I didn't read the install page closely enough.  It again
works perfectly.  Thanks for all your hard work. I wish I knew python well
enough to be able to help.

**Comment by markrickert** [comment]
I figured this would happen a time or two... hence my gigantic text on the change :P https://github.com/JoshuaMulliken/ha-wyzeapi/pull/25

I don't know python either, but it seems simple enough I was able to help with this change even though I zero experience with python :P
