### ISSUE TITLE
[Issue] Wyze Integration Unable to Communicate with Bulbs

### ISSUE THREAD

**Issue by SkoFi** [JoshuaMulliken/ha-wyzeapi#260]
### Issue
After initially working with full functionality, the HA integration becomes unable to power on Wyze bulbs. Once in this state, Reloading the Integration within HA (at a minimum) is required to restore function. Integration continues to work properly for a period of time, then after powering bulbs off, and a period of ~18 hrs elapses, return to the non-communicative state, repeatably--unclear when actual onset within 18 hrs is.

### Debug
Recommended debug log was included, and HA log only indicate the following on attempt to toggle bulbs whilst unresponsive:

    Logger: homeassistant.components.light
    Source: helpers/entity_platform.py:692
    Integration: Light (documentation, issues)
    First occurred: 6:35:31 AM (1432 occurrences)
    Last logged: 6:31:04 PM
    
    Updating wyzeapi light took longer than the scheduled update interval 0:00:30

Integration was un-installed and re-installed but it did not clear the issue. Only reloading the Integration (or restarting the host) restores function.

### Configuration
HA: core-2021.9.6
OS: Home Assistant OS 6.3
OS Version: 5.10.17-v7

**Comment by JoshuaMulliken** [comment]
So if you have a lot of bulbs you might be hitting the rate limit. We are working on a solution to stay under the limit here soon. Btw what version are you using?

**Comment by SkoFi** [comment]
Ah ok, so this may be a noob issue on my part--I thought I had updated all
of HA system, but realized I hadn't updated your integration via HACS (just
core/OS/etc.). I had been running Wyze ver. 2021.05.21, and just recently
updated to Head. Doesn't explain why suddenly started having the issue with
unresponsiveness, but I'll just start by monitoring over next couple of
days and see if the updates resolve my issue, and mark issue resolved if so
(or get back to you if not).

Thanks for responding,
Slavko

**Comment by yoinx** [comment]
Definitely recommend updating via HACS. Many of the changes right now require changes in the backend that is pulled from PyPi during HACS updates, but it doesn't really do this if you're manually updating the integration. It seems that HomeAssistant only pulls manifest requirements during the initial installation of an integration.

**Comment by SkoFi** [comment]
Issue was completely resolved by updating the Wyze Integration in HACS to Head.
