### ISSUE TITLE
[Bug] Unable to add Wyze integration to Home Assistant

### ISSUE THREAD

**Issue by v-tank** [JoshuaMulliken/ha-wyzeapi#267]
Description: When I try to add Wyze to my integrations, the modal immediately closes. The logs say the following:

```
Logger: homeassistant.config_entries
Source: config_entries.py:537

Error occurred loading configuration flow for integration wyzeapi: cannot import name 'ConfigEntryAuthFailed' from 'homeassistant.exceptions' (/usr/src/homeassistant/homeassistant/exceptions.py)
```

Inspecting the Network tab, I see that the POST call to `https://*.duckdns.org/api/config/config_entries/flow` returns a 404 with the response:
```
{"message": "Invalid handler specified"}
```

Please let me know what I'm doing wrong. I've tried to install different versions of the integration but have not been successful. Thank you.

**Comment by yoinx** [comment]
Are you installing via HACS per the recommended method?

**Comment by v-tank** [comment]
I did install it using the instructions on the repo. Anyways, I ended up redoing my entire HA setup and now it seems to be working, so I'll close this issue. Thanks.
