### ISSUE TITLE
[Bug] Plugs don't update their state

### ISSUE THREAD

**Issue by drinfernoo** [JoshuaMulliken/ha-wyzeapi#276]
**Describe the bug**
My plugs (both the old and new version) have been having trouble updating their state when toggled in HA. The device responds, in most cases, but the entity either never updates or takes a very long time. Toggling them in the Wyze app also affects the device, but the HA entity's behavior appears the same.

My further comments below my log seem to indicate that the behavior is correct (or with minimal delay) for some time after a reboot, but apparently stops working after some hours.

**To Reproduce**

1. Toggle a Wyze Plug entity.
2. Wait.

**Expected behavior**
Plug entities should update when toggled.

**System configuration**
System: Home Assistant OS 
HA Version: 2021.10.6
WyzeApi Version: 2021.10.2

**home-assistant.log**

From a fresh reboot with the logging configuration for the readme, and attempting to toggle one plug from on to off:
https://www.toptal.com/developers/hastebin/noliqotahu.py

Curiously, the entity did update here (after a small delay), after having not updated overnight when I turned it off before bed.

1. Turned plug off at night, entity never updated
2. Reloaded integration, which updated the entity to off
3. Turned entity on this morning to test before opening issue, entity never updated
4. Rebooted with logging configuration in place, entity updated to on
5. Turned entity off to get log, entity updated after some time

**Comment by yoinx** [comment]
I don't really see anything wrong in your log right off-hand. Which version of the integration are you?

the entities should automatically update as soon as you toggle the switch. We had a version that we released with a bug where they weren't updating correctly when toggled a few weeks back after changing how we were calling the update functions. I can't remember which version that was, but if you're not on the latest (2021.10.2, it could be related to that.

**Comment by drinfernoo** [comment]
I'm running the latest version (2021.10.2), and have 15 entities, between plugs, cameras, and lights.

My lights seem to be responding correctly (usually, though sometimes not as well), but I don't really use the entities for cameras, as I keep them always on, and use some of them with Frigate anyways.

I have 7 plug entities, and they all seem to be "inconsistent" in their behavior... where they sometimes update correctly, and sometimes don't.

**Comment by yoinx** [comment]
Thanks. Yeah, that should be well below any numbers that should cause issues. I really only use the integration to control my lock, but I'll try to mess with my plugs in it later on today to see if I can reproduce and figure out what's going on.

**Comment by yoinx** [comment]
@drinfernoo simple fix, if you know how to change the 2 lines in your local source, you could give it a test. I'd imagine it should be merged and all that in the next couple days, weekend/halloween and all that.

**Comment by drinfernoo** [comment]
I'll give it a try shortly 👍

**Comment by drinfernoo** [comment]
Seems to be working now, from a quick test after adding those two lines 👍 Thanks for the quick fix!
