### ISSUE TITLE
[Bug] Likely user error: Cannot log in - Unknown User Error Occurred

### ISSUE THREAD

**Issue by seanbaugh** [JoshuaMulliken/ha-wyzeapi#285]
**Describe the bug**
Noob here - my apologies. Successfully installed Wyze integration, however on login, I get an "Unknown error occurred." Password and username are correct - double-checked.

**To Reproduce**

**Expected behavior**
Wyze loin. 

**System configuration**
System: HA Core Mac
HA Version: 2021.11.2
WyzeApi Version: ? Wasn't offered one.

```

**Comment by yoinx** [comment]
Assuming that you installed through HACS, I would say give it a little while and try again. Sometimes wyze has login issues.

If you didn't install through HACS, you're probably missing the library that this integration needs.

**Comment by seanbaugh** [comment]
Thanks - -yes, installed through HACS. I’ll try again this afternoon.

**Comment by yoinx** [comment]
> Thanks - -yes, installed through HACS. I’ll try again this afternoon.

any luck when you tried again?

**Comment by yoinx** [comment]
Since there's no response here, I'm assuming that this resolved itself.

**Comment by seanbaugh** [comment]
It took me awhile since I actually decided to bypass these issues and install a new instance of HA on another machine. Seems to work perfectly now. Thanks for your help. Must have been my previous installation.

**Comment by ams3401** [comment]
Hi, I'm getting the following error all of the sudden. It's been working flawlessly for months. Login credentials did not change. I deleted the integration and re-installed but the issue persists.

```
This error originated from a custom integration.

Logger: wyzeapy.wyze_auth_lib
Source: custom_components/wyzeapi/config_flow.py:59
Integration: wyzeapi (documentation, issues)
First occurred: 11:22:44 AM (11 occurrences)
Last logged: 11:22:52 AM

Unable to login with response from Wyze: {'description': 'Too many failed attempts. Please try again later.', 'requestId': '2c8814ea-4f7d-4b9a-9aa2-c39919f2186f', 'errorCode': 1000}
Unable to login with response from Wyze: {'description': 'Too many failed attempts. Please try again later.', 'requestId': 'bf9715a3-ef3d-485e-85ad-0535c4963fc2', 'errorCode': 1000}
Unable to login with response from Wyze: {'description': 'Too many failed attempts. Please try again later.', 'requestId': '9913b7e8-3c9a-410e-a99e-6f680a09bc84', 'errorCode': 1000}
Unable to login with response from Wyze: {'description': 'Too many failed attempts. Please try again later.', 'requestId': 'cd675e3c-3b02-4b0b-9a04-38babd2b122a', 'errorCode': 1000}
Unable to login with response from Wyze: {'description': 'Too many failed attempts. Please try again later.', 'requestId': 'a9889f62-a213-45f5-ba99-08125bed1121', 'errorCode': 1000}
```
