### ISSUE TITLE
[Feature Request] Support for light strips

### ISSUE THREAD

**Issue by jvolkheimer** [JoshuaMulliken/ha-wyzeapi#287]
**Describe the solution you'd like**
Basic support for light strips - on/off, scenes, etc.

**Comment by yoinx** [comment]
Are you able to MITM any of the data for these? I don't personally own any of them to be able to collect the data.

**Comment by tony-fav** [comment]
I've got one, but I flashed it over to WLED. I backed up the original firmware so should be able to play with it. How have you been going about doing MITM data collection?

**Comment by yoinx** [comment]
I use mitmproxy on a pi3 then you have to run the app in some way to bypass the certificate pinning. I do it from a rooted Android phone using frida. Then you basically just have to do the things in the app and get the data from mitmproxy

**Comment by kanestapler** [comment]
I have a Wyze Light Strip Pro running out of the box. If anyone has any suggestions on how to track the API info I could get it

**Comment by JoshuaMulliken** [comment]
@kanestapler I have written a blog post on how to get started with OWASP ZAP and a rooted Android phone: https://mulliken.net/blog/intercepting-ssl-pinned-connections-on-android

**Comment by kanestapler** [comment]
@JoshuaMulliken Ahh unfortunately I don't have access to an Android phone. Forgot Wyze doesn't have a web app 😞 Maybe I can find some way using the Android Emulator

**Comment by JoshuaMulliken** [comment]
Apparently you can root a Bluestacks emulator but @yoinx might have more info

**Comment by JoshuaMulliken** [comment]
@kanestapler do you have an iPhone that can be Jailbroken?

**Comment by brg468** [comment]
I was able to get one of these working with a few modifications. It seems to be very similar to a white bulb, but I was able to get the color picker working as well. 

I hadn't pulled the recent change adding local control to lights, so I’ll need to do some more digging on how that might change things.

**Comment by JoshuaMulliken** [comment]
@brg468 if you have it partially working you can go ahead and create a PR and I can help clean it up to get it in a state to merge!

**Comment by brg468** [comment]
@JoshuaMulliken PR's submitted. It seems to work fine using local control. I decided not to update some of the methods upstream `(set_color, set_color_temp`, etc) since it seems like those aren't used anymore since you switched to local control, but I'm not real familiar with the code so let me know what I'm missing.

**Comment by JoshuaMulliken** [comment]
Once a release is available I will close this issue

**Comment by JoshuaMulliken** [comment]
Release 0.1.3 is available!

**Comment by DerangedWifi** [comment]
Sorry, reopening. Any chance for support of the pro version of the light strip?
