### ISSUE TITLE
[Feature Request] Wyze Floodlight

### ISSUE THREAD

**Issue by Lukejb14** [JoshuaMulliken/ha-wyzeapi#290]
Basic Floodlight support. (On/off, maybe brightness support)

**Comment by yoinx** [comment]
Same questions as here: https://github.com/JoshuaMulliken/ha-wyzeapi/issues/287

We can only implement for devices we own unless someone can MITM the data and test for us.

**Comment by dmkjr** [comment]
@yoinx I own one of these.  If you could provide some instructions how to get you what you need, I'm in to help.

**Comment by yoinx** [comment]
@dmkjr 

You basically just need a rooted or jailbroken device, setup a MITM proxy on something with wifi and an internet connection (I use a raspberry pi usually, but you could probably do it with a laptop or something). Install the MITM SSL cert, Then you use a tool like Frida to bypass the app's SSL pinning protection. Anything you do in the app will show up in the proxy. So you basically just perform the actions in the app and record what is being sent back and forth.

**Comment by wilg** [comment]
I have the Floodlight + Camera and I would love to be able to control the light on it.

**Comment by jdeath** [comment]
Here is the mitm. Hopefully you can add floodlight on and off now.

I think I got off and on right. Weird that 2 is on and 1 is off. Let me know if you need anything I XXX'd out. 

On:
2022-03-14 22:06:31 POST https://54.189.12.237/app/v2/device/set_property
                        
Content-Type:     application/json
Content-Length:   547
User-Agent:       Dalvik/2.1.0 (Linux; U; Android 12; sdk_gphone64_x86_64 Build/SE1A.220203.002.A1)
Host:             api.wyzecam.com
Connection:       Keep-Alive
Accept-Encoding:  gzip
JSON                                                                                                            [m:auto]{
    "access_token": "XXXXXX",
    "app_name": "com.hualai",
    "app_ver": "com.hualai___2.28.2.111",
    "app_version": "2.28.2.111",
    "device_mac": "XXXXXXXX",
    "device_model": "WYZE_CAKP2JFUS",
    "phone_id": "XXXXXXX",
    "pid": "P1056",
    "pvalue": "2",
    "sc": "XXXXX",
    "sv": "XXXXX",
    "ts": XXXXX
}

Off:
pvalue: 1
