### ISSUE TITLE
[Feature Request] Light Transition and/or Effects

### ISSUE THREAD

**Issue by etchings13** [JoshuaMulliken/ha-wyzeapi#291]
Not sure if this is doable but hoping there might be a way to support the "transition" function for lights - this would allow the lights to change color with a smooth delay. Most other smart lights I've tried support this function. Even better would be "effects" such as colorloop!

**Comment by yoinx** [comment]
As far as I know, this is not supported by wyze. In order for us to support this we would have to basically hammer their servers with repeated commands... Which isn't going to happen.

**Comment by etchings13** [comment]
Bummer! Thanks for the response, I'll be on the lookout for it in the Wyze app - maybe I'll also try to request it from their support team.
