### ISSUE TITLE
[Bug] cant add repo

### ISSUE THREAD

**Issue by lucifudge** [JoshuaMulliken/ha-wyzeapi#305]
**Describe the bug**
cant add repo manually, when searching list for "wyze", repo comes up but fails when trying to install

**System configuration**
System: has os on pi4
HA Version: 
WyzeApi Version: 

**home-assistant.log**

```
<Integration JoshuaMulliken/ha-wyzeapi> GitHub returned 404 for https://api.github.com/repos/JoshuaMulliken/ha-wyzeapi/git/trees/2021.11.1
 <Integration JoshuaMulliken/ha-wyzeapi> No file found 'custom_components/None/manifest.json' 
 No content to download 
```

**Comment by JoshuaMulliken** [comment]
Are you installing through HACS? This is not an addon this is a custom integration

**Comment by lucifudge** [comment]
> Are you installing through HACS? This is not an addon this is a custom integration

yes

**Comment by JoshuaMulliken** [comment]
Something is wrong with your setup because it is trying to find the integration at: `No file found 'custom_components/None/manifest.json'`

The `manifest.json` is at `custom_components/wyzeapi/manifest.json` so I am not sure what is wrong with that. It is working for me but I would recommend filing this issue with HACS.

**Comment by LigerXT5** [comment]
He's not the only one. I just got a wyze outdoor dual outlet, went to add Wyze to Home Assistant, only to find out Wyze isn't supporting Home Assistant. Found your Wyze Custom Component, and... Well the same as Joshua. Though, I don't have logs (yet, about to go look where they appear), it doesn't add as far as I can tell.

When I click Download Repository, all I get is the following message:

repository.note_downloaded '/config/custom_components/wyzeapi'
Remember that you need to restart Home Assistant before changes to integrations (custom_components) are applied.

I've restarted HomeAssistant, still don't see it anywhere in integrations or Addons.

**Comment by dinan5** [comment]
I am having the same issue.

**Comment by yoinx** [comment]
@JoshuaMulliken ... What did you do to all your old tags in the repo? 

This tree still works in my clone because I still have the old tags. For some reason, you only have one here now.

**Comment by foortizs** [comment]
I{m just seeing the same issue:
<Integration JoshuaMulliken/ha-wyzeapi> No file found 'custom_components/None/manifest.json'
9:23:21 PM – (ERROR) HACS (custom integration)
<Integration JoshuaMulliken/ha-wyzeapi> GitHub returned 404 for https://api.github.com/repos/JoshuaMulliken/ha-wyzeapi/git/trees/2021.11.1
9:23:21 PM – (ERROR) HACS (custom integration)

**Comment by thejeffreystone** [comment]
Yep, looks like something changed between 2021.11.1 and now. I'm not sure when the error started for me.  But I am getting it as well. The add-on appears to work, but my HACS installed version stopped seeing updates. 

Looks like a tag it was pointed to is no longer there. 

```
2021-12-11 22:23:30 ERROR (MainThread) [custom_components.hacs] <Integration JoshuaMulliken/ha-wyzeapi> GitHub returned 404 for https://api.github.com/repos/JoshuaMulliken/ha-wyzeapi/git/trees/2021.11.1
2021-12-11 22:23:30 ERROR (MainThread) [custom_components.hacs] <Integration JoshuaMulliken/ha-wyzeapi> No file found 'custom_components/None/manifest.json'
```

When I go to Redownload in HACS this is what I get. 

<img width="431" alt="Screen Shot 2021-12-11 at 10 32 24 PM" src="https://user-images.githubusercontent.com/768082/145699209-2bb9e18d-f567-4fcf-af84-c611e3263797.png">

I dont see references to any of these in the GitHub repo. So not sure what changed but something has gotten out of sync.

**Comment by TheKoob** [comment]
Also experiencing the same issue, identical error message. Just tossing in my two cents.

**Comment by JoshuaMulliken** [comment]
Everyone there is a new stable release available, so that should resolve this issue. You might have to update the info and redownload manually.

Sorry for the mix up I decided to move to SemVer due to some tooling issues, and in deleting the old tags, I accidentally created this issue. I apologize for the inconvenience.

**Comment by dinan5** [comment]
Thank you! Always so responsive!

**Comment by foortizs** [comment]
Thanks a lot!
