### ISSUE TITLE
Unable to install and making it work

### ISSUE THREAD

**Issue by dave-dube** [JoshuaMulliken/ha-wyzeapi#307]
i'm new to this custom integration.  I try to install via HACS but not working.  doesn't matter the version i'm installing (3 version is available in the drop list)... all do the same.
- I Click Download
- Get the generic message from HACS asking me to restart
- i restart

So i never receive any box asking me to enter my Wyze Account + Password.  Am i doing something wrong ?

i would expect a box asking me my Wyze Credentials....

Additionnal Info:
  even if i'm adding debug log level in my configuration file, nothing usefull is logged after a restart...  only log i get is HA telling me that this custom integration has been found and not tested by HA.....  
here is the log i get:
2021-12-12 20:28:36 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

Docker
HA Version: 2021.12
WyzeApi Version: 0.1.1

**Comment by yoinx** [comment]
It may be unclear in the instructions... But like all HACS integrations once you restart the integration it becomes available to install in HA. Installing it from HACS just adds it as an available integration in HA.

**Comment by dave-dube** [comment]
Ho... sorry for that dummy question.. you're right!  I added the "Wyze Home Assistant" integration, and yes i got the boxes for my user + password.  Thanks!  
But still have issue.  After entering my credentials, the only device detected during this process, is a Keypad.. but i don't have any keypad.   In fact, i have a gateway and a door Lock.
After that process, i can see this integration contain 1 device. And this device name is exactly the same name as my Door Lock.  Meaning it seem he found the lock.  And the contain of that device show me 3 entities:  
- my door lock
    it seem its exatly my door lock, but it stay "unavailable".
- Lock Battery
    this entity seem perfect and give me my door lock battery status.  good.
- Keypad Battery
   This entity is disable and it make sense because i have no keypad!  

i tried to restart HA.... deleting integration and adding it again... but always the same behavior.  The adding process is detecting a Keypad... but is creating my Door lock device. But the Door Lock entity is always disable

Am i doing something wrong ?
Thanks for you help

**Comment by dave-dube** [comment]
Hum.. forget my last comment !!!   i remove everything from Wyze app, and repaired everything again... and now... everything is working fine.  Thanks for your help and great job guys!  It worked pretty well !!

The only improvement i could suggest is the Door position sensor.  Right now, no entity has been created to show the door position (open vs closed)

Thanks again !
