### ISSUE TITLE
Deprecation warning in 2021.12.2

### ISSUE THREAD

**Issue by ejpenney** [JoshuaMulliken/ha-wyzeapi#308]
Hi,

I'm seeing these in 2021.12.2:

`Entity lock.front_door (<class 'custom_components.wyzeapi.lock.WyzeLock'>) implements device_state_attributes. Please report it to the custom component author.`

So, this is me notifying the custom component author.

**Comment by yoinx** [comment]
Thanks. It's actually in more than just the lock.

"device_state_attributes" in all the entities just needs to become "extra_state_attributes".

Appreciate the heads up. 

As a side note, this would actually be a good first contribution for someone looking to try getting involved as it *should* basically be a find/replace style change.

**Comment by ejpenney** [comment]
Yup, you're right I should have specified, I've got 20 of them in my log, just grabbed the first one for the C+P.

As for contributing _/shrug_, why the heck not.  You're right, it looks straight forward.  I submitted a PR: https://github.com/JoshuaMulliken/ha-wyzeapi/pull/309 but I'm not really sure how to test/verify it.  Is there a procedure you folks prefer?

**Comment by JoshuaMulliken** [comment]
@ejpenney I will test it locally and then I will give any feedback required and once it checks out I will push it as a patch! Thanks for contributing.
