### ISSUE TITLE
Delay in Brightness and Temperature value in HA

### ISSUE THREAD

**Issue by jamman9000** [JoshuaMulliken/ha-wyzeapi#31]
**Describe the bug**
Upon turning on the light entity, it takes between 17-25 seconds for the brightness and color_temp attributes to display and populate with their accurate values. While off, the light entity loses the brightness and color_temp attributes (disappear from states page) which might be due to how the component was written, maybe that can be reconsidered. In the UI the color_temp slider disappears while off as well. Seeing that this component is completely synced up with the Wyze API, in theory it should never not know when the bulb is being operated so if it gets turned on via Alexa or app it will push (or this component will pull) the status info from Wyze. Keeping the last known value in the entity seems logical.

**To Reproduce**
1. Go to Developer Tools - States tab
2. Find a light entity from the wyzeapi component, view the state and attributes
3. Click the "i" info circle on the left of the entity name to open the light entity
4. Turn the switch off, observe the attributes disappearing from entity state information.
5. Turn the switch on, observe the brightness and color_temp attributes do not appear in the entity attribute information box for anywhere between 17-25 seconds and the UI sliders for these don't indicate reality for that entire time until the attributes arrive.

**Expected behavior**
Last known brightness and color_temp attributes stay with light entity upon turning the light off so they can be accurately displayed as what the current values are until user changes them. If they're somehow different from what was last known, the same update process used now would correct it - maybe the speed can be improved.

**System configuration**
System: Hass.io in a proxmox VM
HA Version: v0.104.0
WyzeApi Version: v0.4.1

**configuration.yaml**
```yaml
wyzeapi:
  username: !secret wyze_un
  password: !secret wyze_pw
```

**home-assistant.log**
```
Nothing of note to report here
```

**Comment by JoshuaMulliken** [comment]
This is a known problem but I do not expect to work on this. If you would like to investigate I am open to a pull request
