### ISSUE TITLE
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by dony71** [JoshuaMulliken/ha-wyzeapi#319]
I reopen this issue https://github.com/JoshuaMulliken/ha-wyzeapi/issues/272
Digging more, issue not due to python environment
This issue only happened when running hass in virtualenv from systemd
systemd setup follows this link below 
https://community.home-assistant.io/t/autostart-using-systemd/199497
However I try run manually below and no issue
```
source /srv/homeassistant/bin/activate
/srv/homeassistant/bin/hass -c “/home/homeassistant/.homeassistant”
```

**Comment by yoinx** [comment]
This is still an environmental issue, not an integration issue. This integration uses aiohttp which would be handling the SSL cert handshakes.

Please stop opening issues that are environment configuration related at the integration cannot do anything to address that.
