### ISSUE TITLE
[Bug] Locks not Updating Correctly

### ISSUE THREAD

**Issue by dave-dube** [JoshuaMulliken/ha-wyzeapi#322]
When clicking LOCK or UNLOCK button, the lock status is updated pretty close to the right status, but few seconds later, the status is back to the previous state, and again +-5-6 seconds later the state is back to the correct status...

Here is an example:
1- the lock state = LOCKED
2- i click UNLOCK button
3- the state change to UNLOCKED (perfect)
4- and 2-3 seconds later, the state change back to LOCKED  (hum.. wrong)
5- and 5-6 second later again, the state change to UNLOCKED (good now)

So its like the Integration is reading state from Wyze server too rapidly... and getting the old state just before the new state reach the Wyze server.  Maybe the integration should wait maybe few second before calling the API, to make sure the server has the new state ?  just basic idea...

I'm actually running the latest HA and WyzeAPI Integration.  And my lock is configured to use the standard Wyze gateway.  So i can use HA and Wyze App together.

** Sometime, (maybe 1/10) the state behave properly.  meaning i dont have the "step 4"...  Probably come from the fact that the state on the server is update between 2 API call event. i don't know what is the API polling frequency

**Comment by LordNex** [comment]
Don’t know if you knew this but you can use the lock without this integration. You can use Zigbee Home Automation(ZHA), just hit the pair button on the lock again while your searching for Zigbee devices. Of course you need a Zigbee hub or multis stick. I have the Nortek HUBZ1 I think it’s the model. But it’ll do both ZHA and ZWave. Just make sure you use a usb extender cable to get the dongle as far away from any other radio interference.

I originally chipped in to have Josh integrate the lock. But with my crappy sat internet it’s just not responsive enough. So I went with Zigbee. I’m supposed to be getting Starlink in a few months though so I’ll reevaluate it then.


On Jan 1, 2022, at 11:27 AM, dave-dube ***@***.***> wrote:

﻿

When clicking LOCK or UNLOCK button, the lock status is updated pretty close to the right status, but few seconds later, the status is back to the previous state, and again +-5-6 seconds later the state is back to the correct status...

Here is an example:
1- the lock state = LOCKED
2- i click UNLOCK button
3- the state change to UNLOCKED (perfect)
4- and 2-3 seconds later, the state change back to LOCKED (hum.. wrong)
5- and 5-6 second later again, the state change to UNLOCKED (good now)

So its like the Integration is reading state from Wyze server too rapidly... and getting the old state just before the new state reach the Wyze server. Maybe the integration should wait maybe few second before calling the API, to make sure the server has the new state ? just basic idea...

I'm actually running the latest HA and WyzeAPI Integration. And my lock is configured to use the standard Wyze gateway. So i can use HA and Wyze App together.

** Sometime, (maybe 1/10) the state behave properly. meaning i dont have the "step 4"... Probably come from the fact that the state on the server is update between 2 API call event. i don't know what is the API polling frequency

**Comment by dave-dube** [comment]
Yeah i know thanks.  Using ZHA, i'm unable to get the door Status (open or closed).  So for that reason i would stick with Wyze brige. 
 And using the native Wyze app, this sync issue doesn't happen.  It seem to be related to the integration itself.
Thanks

**Comment by LordNex** [comment]
Ye for that I just bought some cheap $10 Aqara Zigbee contact sensors. The more I use ZHA and ZWave. The more I prefer it. That along with ESPHome and some ESP32s. And you can make way better sensors than you can buy and customize them to fit your needs. Especially if you have a 3d printer to make customs enclosures.

Benjamin T Powers

On Jan 2, 2022, at 1:55 PM, dave-dube ***@***.***> wrote:

﻿

Yeah i know thanks. Using ZHA, i'm unable to get the door Status (open or closed). So for that reason i would stick with Wyze brige.
And using the native Wyze app, this sync issue doesn't happen. It seem to be related to the integration itself.
Thanks

**Comment by JoshuaMulliken** [comment]
This is definitely an issue. Please see the conversation from #321 for more details.

**Comment by JoshuaMulliken** [comment]
I think since this is related to #297 I am going to close this in favor of that issue as it is more generic and closer to the problem.
