### ISSUE TITLE
[Bug] <Unable to add ha-wyzeapi repository as an Add-on Repository>

### ISSUE THREAD

**Issue by rickb06** [JoshuaMulliken/ha-wyzeapi#327]
**Inability to add this repository as a custom repository within HASS**

**To Reproduce**

1. From HASS, Go to 'Configuration'
2. Click on 'Add-ons, Backups & Supervisor '
3. Click on 'Add-on Store'
4. Click on the three vertical dots
5. Click on Repositories
6. Paste 'https://github.com/JoshuaMulliken/ha-wyzeapi' into the 'Add' field
7. Click Add
8. *See error below*
![Screenshot_20220120-101407_Chrome](https://user-images.githubusercontent.com/4207493/150368433-928fabb0-deb8-4912-be48-673e7d907ad7.jpg)

**Expected behavior**
Upon adding the https://github.com/JoshuaMulliken/ha-wyzeapi GitHub repository, it should be possible to use the repository as an Add-on Repository, but it is not possible at this time. I have performed this on multiple versions, including the latest to no avail. This may or may not be an issue with HA / HASS's repository manifest formatting or syntax.

**System configuration**
System: HASS and Docker 
HA Version: HASS OS 7.1
![Screenshot_20220120-102843_Chrome](https://user-images.githubusercontent.com/4207493/150369557-8757a085-9b13-4e58-b02d-e0a85e67c8a3.jpg)
![Screenshot_20220120-102820_Chrome](https://user-images.githubusercontent.com/4207493/150369558-1907d2d8-9e13-4520-bec9-a8c15b58a7a6.jpg)
WyzeApi Version: 

**home-assistant.log**
```
22-01-20 10:13:51 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/JoshuaMulliken/ha-wyzeapi repository
22-01-20 10:13:51 ERROR (MainThread) [supervisor.store] https://github.com/JoshuaMulliken/ha-wyzeapi is not a valid add-on repository
22-01-20 10:13:51 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / 4824be1f
22-01-20 10:13:51 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / 4824be1f
22-01-20 10:13:53 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/4824be1f
22-01-20 10:13:53 INFO (MainThread) [supervisor.store] Loading add-ons from store: 64 all - 0 new - 0 remove
22-01-20 10:13:53 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: 4824be1f
22-01-20 10:13:53 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/JoshuaMulliken/ha-wyzeapi
```
I just wanted to add that I appreciate you for putting this crucial (to myself and many others) add-on together and making it possible for me to actually tie my smart home together, allowing me to fully make the plunge into HA, as I have invested a significant amount of money into Wyze products, I know that Wyze could cut us off at any moment, but to date, this incredible little add-on crams an amazing amount of functionality into one single add-on. You are too humble BTW. HA and the wonderful people behind the project(s) are truly awesome individuals and they are collective rockstars, but it wouldn't be worth the struggle sometimes, if it weren't for independent developers who are cranking out add-ons, improvements and generally kick @$$ features every day. Your repository is the only legitimately workable Wyze API integrator, and given the popularity and immense market share jump that Wyze has enjoyed, if goes to show that the reason behind the lack of innovation is due to the difficulty of doing so, and **not** a lack of demand. Bravo sir, well done and ***THANKS AGAIN!***

**Comment by yoinx** [comment]
You don't have to add the GitHub repo. It's already in HACS's listing. You just select it in HACS then add it as an integration in HA. (HACS makes it available, then you add it)

**Comment by brg468** [comment]
Based on his steps listed above I don’t think he’s using HACS. I think that’s the confusion, it can’t be added as an HA Addon, which seems like what he’s trying to do.

**Comment by yoinx** [comment]
> Based on his steps listed above I don’t think he’s using HACS. I think that’s the confusion, it can’t be added as an HA Addon, which seems like what he’s trying to do.

Good point, I read "HASS" as "HACS".

Yeah it won't, and isn't intended to, work directly as a HASS addon. There are ways to make it work without installing HACS, but you'll have pretty consistent issues whenever the library that needs to be updated from pypi for the backend is updated.

**Comment by JoshuaMulliken** [comment]
Yep, this is not an add-on it is a HACS integration. Please install Home Assistant Community Store and you will find this integration there!

Thanks for the kind words @rickb06 !

**Comment by rickb06** [comment]
Sorry guys, I am new to HA and HACS as well, and your help is very much appreciated! I did not realize that there was a distinction between HASS and HACS,  but thanks to you guys, I now know the difference! Thankfully I am a Linux sysadmin, so aside from my airheadedness, I now get it, and got this add-on installed! :) Thanks again, and sorry for the confusion.

**Comment by JoshuaMulliken** [comment]
@rickb06 No worries! Glad you got it working
