### ISSUE TITLE
Switches don't show up on scenes

### ISSUE THREAD

**Issue by yfaber** [JoshuaMulliken/ha-wyzeapi#33]
I have a couple of switches around my house automating some led strips, the switch works already and i can turn on/off trough HASSio... the only thing missing now is adding the switches to a scene, when I try to add them they don't show up there. Is there anything I can do to fix this?

**Comment by yfaber** [comment]
@JoshuaMulliken any ideas on how to fix this?

**Comment by JoshuaMulliken** [comment]
Are you adding the entity into the scene?

**Comment by yfaber** [comment]
Ow hey! The plugs don't show up on the entities tab, because of that I think they don't show up on the scenes tab. 

I have the plugs working fine using your Custom Component.
