### ISSUE TITLE
[Feature Request] Color Bulb Local Control Wiki/Documentation

### ISSUE THREAD

**Issue by motoridersd** [JoshuaMulliken/ha-wyzeapi#350]
I see mentions of this being an option in several issues/notes, but how do we make this work? Is there some documentation I can look at? Even if it's too beta, I'd love to test and report any issues.

**Comment by yoinx** [comment]
I don't have the bulbs and have been away from the project for a bit. 

Maybe the commits (not necessarily the cleanest) might help?

https://github.com/JoshuaMulliken/wyzeapy/commit/b3ff47e0cdf2b3c66ede6bc32eae6bbec1f5dc98#diff-929561a9bd7acff46efdcbbc78f503b2601dc423f2b02be13a6b461599b342afR583

https://github.com/JoshuaMulliken/ha-wyzeapi/commit/eac4d947c318a10ca2620d6d6229523133a46f3f

As far as I can tell, it looks like it's just enabled if it can be.

**Comment by JoshuaMulliken** [comment]
@motoridersd yep, it is opportunistically enabled.
