### ISSUE TITLE
[Bug] Wyze api no longer loads in HA version 2022.3.4f issue>

### ISSUE THREAD

**Issue by sphinxlady** [JoshuaMulliken/ha-wyzeapi#366]
**Describe the bug**
Wyze api no longer loads in HA version 2022.3.4

**To Reproduce**
Updating or a new install seems to work but on restart api fails to load

**Expected behavior**
Api should load which goes without saying.

**System configuration**
System: happens on both proxmox vm  7.1-11 and on rassberry ver 4 8gig
HA Version: 2022.3.4
WyzeApi Version: all version fail to load on even on fresh HA installs.

**home-assistant.log**
 Logger: homeassistant.config_entries
Source: config_entries.py:745
First occurred: 3:01:19 PM (1 occurrences)
Last logged: 3:01:19 PM
Error occurred loading configuration flow for integration wyzeapi: No module named 'custom_components.wyzeapi.const'

Updating previous install causes the error wyze api failed to load.

Bare in mind i could be missing something here as i am mostly blind at the moment as eye surgery got delayed do to covid.

**Comment by JoshuaMulliken** [comment]
I updated and it is working for me... It seems like your wyzeapy install is bad can you attempt a reinstall?

**Comment by sphinxlady** [comment]
Wasn't the integration it was github.

Depending on where you were the install would time out do to a issue on there end.

Seems to have been addressed for the most part and is back to normal.

**Comment by JoshuaMulliken** [comment]
Great! Glad you were able to resolve the problem

**Comment by sphinxlady** [comment]
Thanks .

Certainly a harder one to find it's not like they gone offline they just weren't always responding quickly enough/

Thanks for the hard work.
