### ISSUE TITLE
Motion Motion Sensor Support

### ISSUE THREAD

**Issue by wiinc1** [JoshuaMulliken/ha-wyzeapi#369]
The ability to receive requests from the Wyze motion sensor to create routines based off of the information (e.g. turn on lights).  

Support for version 1 & 2 of the motion sensor would be helpful.

https://www.wyze.com/products/wyze-sense-motion-sensor-v2

**Comment by yoinx** [comment]
Binary sensors lost support due to ddosing wyze's servers. Unfortunately, they're mostly useless if we can't poll them frequently enough.

**Comment by wiinc1** [comment]
Thanks for the response - makes sense.  

Completely disappointed with their closed approach to Wyze.  It has really limited me in what I purchase from them now.
