### ISSUE TITLE
Support camera API?

### ISSUE THREAD

**Issue by roger-** [JoshuaMulliken/ha-wyzeapi#37]
Sorry if this is addressed elsewhere but is the Wyze camera API entirely different or can it be supported?

**Comment by JoshuaMulliken** [comment]
Since you can use rtsp firmware to add the cameras into Home Assistant I will not be implementing the camera in this integration

**Comment by roger-** [comment]
Understood, but normal firmware is still useful to those who want notifications from the cameras.

**Comment by JoshuaMulliken** [comment]
It can be. There are alternative ways of getting notifications from rtsp streams

**Comment by roger-** [comment]
Are you open to PRs?

**Comment by JoshuaMulliken** [comment]
For the core functionality and devices with no alternatives but unfortunately, since I wouldn't be able to maintain this, I am hesitant to merge any code for handling the camera. If someone is willing to maintain that portion then that would be great though.

**Comment by bmcclure** [comment]
While I can understand your position, supporting cameras would be really nice. Wyze is adding more features into their mainline firmware that they are not, at least at this time, adding into the RSTP firmware. So using RSTP streams is not really a good replacement for accessing the camera streams via API.

The alternative, which many people are doing currently, is using TinyCam or another camera streaming app that supports Wyze, but that is adding a lot of extra pieces into the mix that wouldn't be necessary if this plugin did support cameras directly.
