### ISSUE TITLE
Battery level

### ISSUE THREAD

**Issue by LokilloMM** [JoshuaMulliken/ha-wyzeapi#381]
I have a page with all the battery levels so I can see at a glance if any devices need new batteries or a charge. 
It will be great to be able to add the battery level of the door bell cam

**Comment by JoeSchubert** [comment]
Sorry for the really delayed response on this. I'm just getting back to the project and just recently got a doorbell camera. This appears to be fairly easy to get as every camera has an "electricity" field within device_params that holds this value. However, I will say that I would question the reliability of this value. I personally hardwired my doorbell camera and my "electricity" field shows "84" currently and I see no other fields that would indicate that it is on battery or wired power. 

On cameras without a battery, this field is an empty string. Perhaps we could simply check if this field is empty and if not present the battery percentage?

**Comment by JoeSchubert** [comment]
It's been a week and this appears to be working as far as I can tell. I'm going to close it as stale, please re-open if you are still experiencing the issue.
