### ISSUE TITLE
[Feature Request] WYZE-Bridge support

### ISSUE THREAD

**Issue by Codel1417** [JoshuaMulliken/ha-wyzeapi#383]
Basically if wyze bridge is installed as an addon automatically add the camera feeds to home assistant. Wyze bridge uses a simple layout of URLs that is just based on the camera name.

Cameras would only need the generic IP camera integration. 
RTSP, RTMP, & HLS are supported.

 there is the alternative of just manually adding the generic IP camera integration for each camera

**Comment by TheFlatworm** [comment]
+1 for lock access through Wyze WiFi bridge.

**Comment by wystewart** [comment]
+1 but it would be even better if this integration used the bridge RTSP and snapshot api to expose HA native cameras.  Right now to turn off and on the cameras, the switch entities of the integration must be used, but it would be much cleaner if these were natively linked to the camera.turn_on and turn_off.

**Comment by JoeSchubert** [comment]
I highly doubt that there is any intention of integration support that relies on another API that effectively proxies Wyze's API (even if it does create camera feeds). As there would be no way to ensure that all users have installed the addon/container for this.i actually installed wyze-bridge recently and dropped it as it was too laggy to be useful for me.

@JoshuaMulliken thoughts?

**Comment by JoshuaMulliken** [comment]
Yeah, I think that this is out of the scope for this project
