### ISSUE TITLE
this camera does not always have floodlight

### ISSUE THREAD

**Issue by Geczy** [JoshuaMulliken/ha-wyzeapi#397]
https://github.com/JoshuaMulliken/ha-wyzeapi/blob/2045cb2bcbd4f4005cb66a8292a029860b716463/custom_components/wyzeapi/light.py#L65

i just have a v3 but its being detected as a floodlight cam. how to remove this?

<img width="383" alt="image" src="https://user-images.githubusercontent.com/1036968/179012141-d68c804e-66ad-4fbd-a7c2-a6de4b18a6c7.png">

**Comment by brg468** [comment]
I don't think there's a way to tell if the camera physically has a floodlight attached or not. 

The easiest fix would be to hide or disable the floodlight entity.

**Comment by JoshuaMulliken** [comment]
@Geczy I would recommend you follow the advice provided by @brg468. I am going to close this issue
