### ISSUE TITLE
[baby monitor mode] <allow sound only with screen off>

### ISSUE THREAD

**Issue by spiltmilk1** [JoshuaMulliken/ha-wyzeapi#402]
it would be nice to have a sound only mode that works in the background when using phone in another context and with the screen off.

baby monitor mode to allow you to listen in on a camera while browsing or while phone screen is off to save battery.

**Comment by JoeSchubert** [comment]
I'm confused about what exactly you're looking for here. This sounds more like you were looking to make a suggestion to Wyze for their app?

This integration does not get any data from the cameras, let alone stream anything from them with or without the screen on.
