### ISSUE TITLE
[Bug] <short description of issue>

### ISSUE THREAD

**Issue by santiago990513** [JoshuaMulliken/ha-wyzeapi#412]
**wyze bulbs color won't update status**

**Expected behavior**

**System configuration**
System:

**Comment by santiago990513** [comment]
Hey, thanks for answering, it's working just fine now. The issue was present when controlling the lights through the app the status wouldn't update in home assistant.

**Comment by brg468** [comment]
👍 I think there was a backend fix to address the status updates. Glad to hear its working now.
