### ISSUE TITLE
[Feature Request] Enable or Disable Motion Detection

### ISSUE THREAD

**Issue by rocnydad** [JoshuaMulliken/ha-wyzeapi#415]
This is a request to enable or disable motion detection in a similar toggle fashion to enabling or disabling notification.

Please note - this is not a request to trigger events if motion is detected. The request is to simply turn on or off motion detection.

In the Wyze app you need to have Event Recording enabled in order to select the option to enable or disable motion detection.

This is available in IFTTT

**Comment by brg468** [comment]
I’ve been able to get this working with V3 cameras, but it doesn’t seem to work with my V2 cameras. I am running pretty old RTSP firmware on the V2 cameras so maybe that has something to do with it. I’ll play around with it and see what I can figure out.

**Comment by rocnydad** [comment]
Thanks - I'm most interested in the outdoor V2's    I'd like to disable motion sensing when I'm at home. I'm running stock firmware - not the RTSP install.  Thanks much

**Comment by brg468** [comment]
@rocnydad are you up for testing for me?

If so, download and replace the current `wyzapi` folder inside `custom_components `with the one from [here](https://github.com/brg468/ha-wyzeapi/tree/motion-detection-switch).

Then, download from [here](https://github.com/brg468/wyzeapy/tree/motion-detection-switch) and put the `wyzeapy` folder inside your config folder and restart HA. If all goes well you should see a new switch for motion detection. 

I haven't tested the outdoor cams, all I have is indoor V2's and 3's, but it's working on those with non-RTSP firmware.

**Comment by rocnydad** [comment]
Definitely up to test.  I'll give it a go this weekend.  Thx.

**Comment by rocnydad** [comment]
@brg468 replaced wyzeapi folder and uploaded wyzepy folder to config/ but I'm getting a "not available" alert for the motion detection entity for all 4 of my cams (two outdoor v2s and two indoor v3s) - I did not previously have a wyzepy folder in conflig. I'm relatively new to HA. Is this the right place for that wyzepy folded - do I need to include it in the config.yaml?

**Comment by brg468** [comment]
Are there any relevant logs?

You would not have a wyzeapy folder prior to this, normally it’s downloaded in the background but this should overwrite the original.

**Comment by rocnydad** [comment]
@brg468 sorry for the delayed response, just getting back to this.  I've since rolled to a new version of the core wyze api.  I'll need to reinstall your branch. I generate a ton of logfiles for HA.  Let me know if there's a way to filter the info you specifically are interested in.  Thx

**Comment by brg468** [comment]
Really just anything that references wzyeapi. Particularly on startup there should be something about unable to load if it’s still an issue.

**Comment by Merril-r** [comment]
@brg468 I have couple version 2 and 3 cameras with stock firmware. I would like to assists with testing. Can I still use the links for downloading the beta code you posted in the earlier comments?

**Comment by brg468** [comment]
Yes use the links and instructions above and give it a try!

**Comment by rocnydad** [comment]
@brg468 sorry - haven't had a ton of time to test, but finally got back to it as a way to forget about the Bills . . .

Here's the two logfiles I see

Logger: homeassistant.components.lock
Source: custom_components/wyzeapi/lock.py:149
Integration: Lock ([documentation](https://www.home-assistant.io/integrations/lock), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+lock%22))
First occurred: 7:37:09 PM (1 occurrences)
Last logged: 7:37:09 PM
wyzeapi: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
    await func(*args, **kwargs)
  File "/config/custom_components/wyzeapi/lock.py", line 149, in async_update
    lock = await self._lock_service.update(self._lock)
  File "/usr/local/lib/python3.10/site-packages/wyzeapy/services/lock_service.py", line 18, in update
    device_info = await self._get_lock_info(lock)
  File "/usr/local/lib/python3.10/site-packages/wyzeapy/services/base_service.py", line 499, in _get_lock_info
    device_uuid = device.mac.split(".")[2]
IndexError: list index out of range




Logger: homeassistant.util.logging
Source: util/logging.py:168
First occurred: 7:37:14 PM (21 occurrences)
Last logged: 7:41:23 PM

Exception in handle_camera_update when dispatching 'wyzeapi.camera_updated-D03F2745CFCF': (<Device: DeviceTypes.CAMERA, D03F2745CFCF>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/switch.py", line 440, in handle_camera_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state state = self._stringify_state(available) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 982, in state if (is_on := self.is_on) is None: File "/config/custom_components/wyzeapi/switch.py", line 429, in is_on return self._device.motion AttributeError: 'Camera' object has no attribute 'motion'
Exception in handle_camera_update when dispatching 'wyzeapi.camera_updated-D03F274A48C4': (<Device: DeviceTypes.CAMERA, D03F274A48C4>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/switch.py", line 440, in handle_camera_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state state = self._stringify_state(available) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 982, in state if (is_on := self.is_on) is None: File "/config/custom_components/wyzeapi/switch.py", line 429, in is_on return self._device.motion AttributeError: 'Camera' object has no attribute 'motion'
Exception in handle_camera_update when dispatching 'wyzeapi.camera_updated-D03F275C3018': (<Device: DeviceTypes.CAMERA, D03F275C3018>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/switch.py", line 440, in handle_camera_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state state = self._stringify_state(available) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 982, in state if (is_on := self.is_on) is None: File "/config/custom_components/wyzeapi/switch.py", line 429, in is_on return self._device.motion AttributeError: 'Camera' object has no attribute 'motion'

**Comment by brg468** [comment]
@rocnydad it doesn't seem like you have the updated version of wyzeapy in your config folder. 

Make sure its the one from the branch above (2nd link), and if your downloading it as a zip file make sure you are grabbing the innermost wyzeapy folder and placing that in your config folder. The path to it from the zip should be something like: `\wyzeapy-motion-detection-switch\src\wyzeapy\`. Let me know if that helps.

**Comment by Merril-r** [comment]
@brg468 

Installed the software as per your links.

Changes you made reflect on my side.

Only log error I got was the following:

Logger: homeassistant.components.switch
Source: runner.py:119
Integration: Switch (documentation, issues)
First occurred: 12:48:18 PM (1 occurrences)
Last logged: 12:48:18 PM

Setup of switch platform wyzeapi is taking over 10 seconds.

This was after the reboot. Got this again when I did a reboot.

Notification control working on wyze 2 and wyze 3 cam. I can turn them on and off.

The notification works on cams that have a wyze subscription and those that don't.

Have picked up the following:
- Siren control shows up for wyze 2 cam and that is not suppoted.
- Floodlight shows up on wyze 3 even if there is no spot light connected.
- Sometime when you turn the notifications off/on in the wyze app the change does not reflect in HA - This could be a wyze cloud issue.
- There is an option turn of notifications that I assume is a global switch for all cams., that does not appear to work,

I will continue testing on my side.

I would like to thank you for the effort you have put in on this integration feature, This is something I have wanted even before I got involved with home assistant.

Secondly I would like to thank you for giving me the opportunity to help with the testing.

**Comment by rocnydad** [comment]
> @rocnydad it doesn't seem like you have the updated version of wyzeapy in your config folder.
> 
> Make sure its the one from the branch above (2nd link), and if your downloading it as a zip file make sure you are grabbing the innermost wyzeapy folder and placing that in your config folder. The path to it from the zip should be something like: `\wyzeapy-motion-detection-switch\src\wyzeapy\`. Let me know if that helps.

Hey @brg468 thank you for your continued help with this.   I repulled both the api and apy folders from the links above 

I put the api files into  /root/config/custom_components/wyzeapi/  (including the translations sub directory)
I put the py files into  /root/config/wyzepy/  (including the services sub directory)

I restarted and am still getting the same errors.  



Logger: homeassistant.components.lock
Source: custom_components/wyzeapi/lock.py:149
Integration: Lock (documentation, issues)
First occurred: 8:32:59 AM (2 occurrences)
Last logged: 8:35:07 AM

wyzeapi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
    await func(*args, **kwargs)
  File "/config/custom_components/wyzeapi/lock.py", line 149, in async_update
    lock = await self._lock_service.update(self._lock)
  File "/usr/local/lib/python3.10/site-packages/wyzeapy/services/lock_service.py", line 18, in update
    device_info = await self._get_lock_info(lock)
  File "/usr/local/lib/python3.10/site-packages/wyzeapy/services/base_service.py", line 499, in _get_lock_info
    device_uuid = device.mac.split(".")[2]
IndexError: list index out of range



Logger: homeassistant.util.logging
Source: util/logging.py:168
First occurred: 8:33:05 AM (8 occurrences)
Last logged: 8:34:39 AM

Exception in handle_camera_update when dispatching 'wyzeapi.camera_updated-D03F2745CFCF': (<Device: DeviceTypes.CAMERA, D03F2745CFCF>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/switch.py", line 440, in handle_camera_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state state = self._stringify_state(available) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 982, in state if (is_on := self.is_on) is None: File "/config/custom_components/wyzeapi/switch.py", line 429, in is_on return self._device.motion AttributeError: 'Camera' object has no attribute 'motion'
Exception in handle_camera_update when dispatching 'wyzeapi.camera_updated-D03F275C3018': (<Device: DeviceTypes.CAMERA, D03F275C3018>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/switch.py", line 440, in handle_camera_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state state = self._stringify_state(available) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 982, in state if (is_on := self.is_on) is None: File "/config/custom_components/wyzeapi/switch.py", line 429, in is_on return self._device.motion AttributeError: 'Camera' object has no attribute 'motion'
Exception in handle_camera_update when dispatching 'wyzeapi.camera_updated-D03F274A48C4': (<Device: DeviceTypes.CAMERA, D03F274A48C4>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/switch.py", line 440, in handle_camera_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state state = self._stringify_state(available) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 982, in state if (is_on := self.is_on) is None: File "/config/custom_components/wyzeapi/switch.py", line 429, in is_on return self._device.motion AttributeError: 'Camera' object has no attribute 'motion'

**Comment by brg468** [comment]
@Merril-r, thanks for testing this. Quick question, you mentioned the notification switch several times, but that is not a new feature on this branch, its been in the production version for a while now. Did you have a motion detection switch show up for these cameras, and if so were you able to test that out? That should be the only new feature here. As far as the other notes:

- You're right, there should not be a siren for V2 cams. I'll take a look at removing that.
- As far as I can tell there is no way via the API to tell if a floodlight is physically attached to a camera, so by default the switch is added. Easiest fix there is just disable the entity if its not appropriate. 
- I have seen that occasionally and it seems to be due to the data on the Wyze side not being correct.
- The stand alone notification switch is actually for push notifications for the app itself. At least on iOS it does seem to work, although I've never personally played around with it much.

**Comment by brg468** [comment]
@rocnydad ok I'm not sure why that's not working. 

I updated the manifest file to hopefully pull the dependency directly now. Redownload wyzeapi from [here](https://github.com/brg468/ha-wyzeapi/tree/motion-detection-switch) and place the `wyzeapi `folder in `custom_components` like before. No need for the wyzeapy folder in config anymore (go ahead and remove it if its still there, just in case). Hopefully that should work for you.

**Comment by rocnydad** [comment]
@brg468   Still the same situation - the motion entity is visible but not active.  I see this across two outdoor cam V2s, a pancam, and the garage cam (which uses the cam v3).  Should I try a full uninstall and reinstall of the WYZE integration?

**Comment by brg468** [comment]
@rocnydad sure give it a try. I’m not sure why it’s not working. 

Worst case just re-install from HACS later and it will put everything back to normal.

**Comment by rocnydad** [comment]
@brg468 Very strange - eventually just rolled back to original from HACS.  It could see the motion switch but it was always unavailable.  

Sorry I couldn't help more . . .  I will watch for this though.  Definitely a needed feature.

Thanks for you work

**Comment by Merril-r** [comment]
> @Merril-r, thanks for testing this. Quick question, you mentioned the notification switch several times, but that is not a new feature on this branch, its been in the production version for a while now. Did you have a motion detection switch show up for these cameras, and if so were you able to test that out? That should be the only new feature here. As far as the other notes:
> 
> * You're right, there should not be a siren for V2 cams. I'll take a look at removing that.
> * As far as I can tell there is no way via the API to tell if a floodlight is physically attached to a camera, so by default the switch is added. Easiest fix there is just disable the entity if it’s not appropriate. (Actually I don’t really know if that’s true, but I don’t have a floodlight version to compare).
> * I have seen that occasionally and it seems to be due to the data on the Wyze side not being correct.
> * The stand alone notification switch is actually for push notifications for the app itself. At least on iOS it does seem to work, although I've never personally played around with it much.

@brg468 I got mixed up between the two options. :-)  I tested the motion detection and its working on my side for both the version 2 and version 3 cam,

Thanks for the replies to my other findings. I will just disable the spotlight entity.

Will be great if you can remove the siren on V2 cams,

**Comment by JoshuaMulliken** [comment]
> Will be great if you can remove the siren on V2 cams,

This got merged the other day and I will be publishing a new release soon! Thanks to @brg468!

**Comment by JoshuaMulliken** [comment]
This has been released in 0.1.16
