### ISSUE TITLE
[Bug] Setup failed for custom integration wyzeapi: Requirements for wyzeapi not found: ['wyzeapy==0.5.13'].

### ISSUE THREAD

**Issue by manofpants** [JoshuaMulliken/ha-wyzeapi#419]
On update through HACS, integration failed to load with this error: Setup failed for custom integration wyzeapi: Requirements for wyzeapi not found: ['wyzeapy==0.5.13'].

1. Update Wyze integration to 0.1.14 via HACS.
2. Reboot HA.
3. See errors in log and integration failed to load.

**Expected behavior**
Expected to update successfully

**System configuration**
System: HAOS on Rpi3
HA Version: 2022.10.5
WyzeApi Version: ?

**home-assistant.log**
Logger: homeassistant.setup
Source: setup.py:184
First occurred: 10:45:27 AM (1 occurrences)
Last logged: 10:45:27 AM

Setup failed for custom integration wyzeapi: Requirements for wyzeapi not found: ['wyzeapy==0.5.13'].

**Comment by manofpants** [comment]
Weird. I rebooted (again) and it's working fine.

**Comment by JoshuaMulliken** [comment]
@manofpants it is likely that your package cache was not up to date. I will close this issue
