### ISSUE TITLE
Send and receive correct CCT

### ISSUE THREAD

**Issue by icemanch** [JoshuaMulliken/ha-wyzeapi#42]
Currently the CCT value is translated on a scale.  Because mireds isn't linear it doesn't accuretly communicate the request CCT from HA to Wyze.  I tinkered with the code and added the below that seems to work.  I'm not a python coder so it might not be the best implementation.

This is to send to Wyze.
```
           if self._colortemp:
                if self._colortemp >= 370:
                    colortemp = 2700
                elif self._colortemp <= 153:
                    colortemp = 6500
                else:
                    colortemp = 1000000/self._colortemp
                    
                property_list.append({"pid": "P1502", "pvalue": colortemp})
```

This is to receive from Wyze.

```
                elif item['pid'] == "P1502":
                    self._colortemp = 1000000/int(item['value'])

```

This removes the translate from the calculation of the CCT.

**Comment by JoshuaMulliken** [comment]
This works great! I will add this in to the project.
