### ISSUE TITLE
[Feature Request] Support for double-, triple-, and hold-press actions on Wyze Switch

### ISSUE THREAD

**Issue by myRice87** [JoshuaMulliken/ha-wyzeapi#423]
It would be great to be able to detect double-, triple-, and hold-press actions on the Wyze Switch. These are supported in the native app and make controlling several lights from a single switch very easy.

For a specific use case, I have a switch that controls a traditional light fixture above my kitchen table with a single-press. Using IFTTT applets, I'm then also able to turn on my under-cabinet lighting which runs off of a Tuya controller with a double-press, and turn off both sets of lights with a hold-press.

Since I've been gradually migrating everything into HA, I'd love for a way to keep this behavior.

**Comment by JoeSchubert** [comment]
Without the IFTT applets, how would you get the actions from this? Wyze App Rules?

I don't have any Wyze switches and don't have much interest in getting any. I'd honestly stick with the IFTT integration as you'll be cloud dependent either way.

As far as I can tell from back when we had throttling issues with Wyze, it seems that IFTTT has some unthrottled method to interact with Wyze... so they'll even probably be faster responding than anything that we can reverse engineer.

**Comment by myRice87** [comment]
Ah, it seems I had a fundamental misunderstanding of how this integration works. Thanks for clarifying. I managed to get it working w/ an IFTTT applet containing a webhook that calls my HA instance so I can toggle my local devices. Kind of a circuitous path, but I suppose it can't be avoided as long as I'm running this Wyze switch. Can consider this issue closed now.
