### ISSUE TITLE
Wyze Thermostat Humidity

### ISSUE THREAD

**Issue by IceDraken** [JoshuaMulliken/ha-wyzeapi#424]
Is there any way to pull the humidity off the thermostat and into the plug in so HA can reference it? 
Right now I can only check it in the wyze app and turn on a humidifier.  Was hoping to automate it.

**Comment by whundahl** [comment]
Yes there is. I was able to do this in the current release. Here is how I went about it. I created two automations in home assistant that query the climate attribute for the thermostats humidity, then told HA to turn on the plug or outlet for the humidifier.


![image](https://user-images.githubusercontent.com/31379657/208174018-a8633af8-8344-4e61-aae7-4d4928a894ba.png)

**Comment by JoeSchubert** [comment]
@IceDraken did this solution work for you? If so, I'll close this issue.

**Comment by JoeSchubert** [comment]
Closing as no response received. Please reopen if the above did not work for you.
