### ISSUE TITLE
Repo not useable

### ISSUE THREAD

**Issue by rbees** [JoshuaMulliken/ha-wyzeapi#43]
Virtual Box VDI
System | HassOS 3.13
-- | --
Deployment | production

Setup May 1, 2020

20-05-01 14:34:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-05-01 14:34:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/JoshuaMulliken/ha-wyzebulb repository
20-05-01 14:34:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-05-01 14:34:27 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-05-01 14:34:27 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/87977a50/repository.json: [Errno 2] No such file or directory: '/data/addons/git/87977a50/repository.json'
20-05-01 14:34:27 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/87977a50/repository.json
20-05-01 14:34:27 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove

**Comment by JoshuaMulliken** [comment]
This looks like a HACS issue. Have you filed an issue there?

**Comment by JoshuaMulliken** [comment]
I've closed this issue because it doesn't appear to be relevant. If you have additional information please feel free to open a new issue or reply to this one.
