### ISSUE TITLE
[Feature Request] Wyze Robot Vacuum Integration

### ISSUE THREAD

**Issue by bluedefense** [JoshuaMulliken/ha-wyzeapi#440]
A useful feature request would be the integration of their Robot Vacuums. Start/stop/dock/display maps and rooms and allow to start vacuuming.

As always, your support is appreciated.

**Comment by nameetpai** [comment]
I second this. If I was to scope this project down maybe we could start with just start/stop/dock and current status. 

Maps and rooms sound a bit complicated and I can't imagine any real value of being able to see it in home assistant vs Wyze app other than minimizing the confusion of having to deal with so many different apps by everyone in the household. May be phase 2 could include being able to just list the room names and directing the bot to clean specific rooms.

I'm also willing to offer development help but might need a contribution primer?

**Comment by nameetpai** [comment]
Just came across another issue asking for this same feature and there's a healthy conversation running there. 

https://github.com/JoshuaMulliken/ha-wyzeapi/issues/281

@bluedefense you might want to follow that thread and close this issue as a dupe

**Comment by bluedefense** [comment]
> Just came across another issue asking for this same feature and there's a healthy conversation running there.
> 
> #281
> 
> @bluedefense you might want to follow that thread and close this issue as a dupe

Thank you, sir. I'll take a look and close this as necessary.
