### ISSUE TITLE
[Bug] Cannot add repo to Add-ons store

### ISSUE THREAD

**Issue by Responseless** [JoshuaMulliken/ha-wyzeapi#444]
**Describe the bug**
Cannot add repository in home assistant

**To Reproduce**

1. Go to Add-on Store
2. Click on Repositories
3. Paste "https://github.com/JoshuaMulliken/ha-wyzeapi" and click Add.
4. See error "https://github.com/JoshuaMulliken/ha-wyzeapi is not a valid add-on repository"

**Expected behavior**
To add the repo.

**System configuration**
System: N/A
HA Version: 2023.1.1
WyzeApi Version: N/A

**home-assistant.log**
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 12:22:48 PM (1 occurrences)
Last logged: 12:22:48 PM

Failed to to call /store/repositories - https://github.com/JoshuaMulliken/ha-wyzeapi is not a valid add-on repository

**notes:**
Im guessing you may require a repository.json file?

**Comment by JoeSchubert** [comment]
This may need to be clarified in the readme.

This is added as a repo in HACs, this it being mentioned in step 1, not through HA's AddOn store.

**Comment by JoshuaMulliken** [comment]
I feel like this is already discussed here: https://github.com/JoshuaMulliken/ha-wyzeapi#installation-hacs---highly-recommended

I will reopen this if we need to do additional clarification. If someone has better documentation feel free to open a PR
