### ISSUE TITLE
[Bug] cameras are missing binary sensor for motion detection

### ISSUE THREAD

**Issue by Menz01** [JoshuaMulliken/ha-wyzeapi#447]
**Describe the bug**

cameras are missing motion detection binary sensors

**To Reproduce**

1. Go to settings then devices and settings
2. Click on devices in Wyze integration and then on any camera
3. look in "controls" section
4. motion detection binary sensor is not there

**Expected behavior**

expect to see a motion detection binary sensor that i can use for automations
**System configuration**
System: HAOS on VMWare ESXi
HA Version: 2023.1.4
WyzeApi Version: 

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```

**Comment by JoshuaMulliken** [comment]
This is not supported due to API request limit issues.
