### ISSUE TITLE
[Question]Have you seen this app?

### ISSUE THREAD

**Issue by LordNex** [JoshuaMulliken/ha-wyzeapi#450]
[GitHub - mrlt8/docker-wyze-bridge: WebRTC/RTSP/RTMP/LL-HLS bridge for Wyze cams in a docker container](https://github.com/mrlt8/docker-wyze-bridge)

**Comment by JoeSchubert** [comment]
I have. However, in my testing, the streams tended to be overly laggy. I started rewriting an API bridge in Go that I hope will perform a bit better. But, I have a lot of RL stuff going on that is limiting the time I have to work on that, so it's a bit of a slow side project right now.

However, this seems more like a discussion than an issue. I'd recommend opening it as a discussion. So, I'm going to go ahead and close it as it has nothing to do with an issue in this project.

**Comment by LordNex** [comment]
That's understandable. I wasn't sure where to post so I figured here would be a start. 

So far I haven't been able to get it to work. Although most of my Wyze Cams are on the RSTP firmware and are ported into Frigste well enough. Although I am going to try and use it on my Outdoor Cam as it was the one can I never could find a way to integrate. 

Either way we're still having issues with the fact that most of my IoT devices are on one VLAN and my client devices on another. So he's looking into that. 

And thanks again for all your hard work!

**Comment by JoeSchubert** [comment]
> So far I haven't been able to get it to work. Although most of my Wyze Cams are on the RSTP firmware

Strange. I wonder if that's why. However, this connects via the same library the app uses... so if your app can still connect to this, this container should be able to. In my testing, things could connect and stream... but it was really laggy/buggy. It's a neat concept but I definitely wouldn't rely on it as a reliable video feed as it is.
