### ISSUE TITLE
[Feature Request] Exclusion of devices

### ISSUE THREAD

**Issue by mach7** [JoshuaMulliken/ha-wyzeapi#457]
I'd like to be able to exclude devices from showing up from the devices in HA. Is that currently possible?

Example: I'd like to be able to  utilize everything besides my cameras.

**Comment by brg468** [comment]
Any device can be disabled in the devices page in HA…is that what you’re asking to do?

**Comment by JoeSchubert** [comment]
Closing this as it's a function of Home Assistant to disable devices, as stated above. Since there's been no follow-up, I assume this is a non-issue.
