### ISSUE TITLE
Wyze Lock status not refreshed anymore

### ISSUE THREAD

**Issue by dave-dube** [JoshuaMulliken/ha-wyzeapi#459]
The state of my door lock is not refreshed anymore. i can lock/unlock it via HA without any issue, but when locking/unlocking it manually HA is never refreshed. The only moment HA state is updated is when i reboot HA.  So in summary it get the lock state only once when i restart HA.  After that the state never change.

i'm not 100% sure, but i have feeling it stopped working after the last Wyze maintenance on February 8th.

- Lock/unlock manually the lock and HA state is never refreshed

**Expected behavior**
The lock state should change when i lock/unlock it manually

**System configuration**
System: Supervised
HA Version: 2023.2.4
WyzeApi Version: 0.1.18b1

**home-assistant.log**
using this logger config:
    custom_components.wyzeapi: debug
    wyzeapy: debug
some logs are created when restarting HA, but no additionnal log is created after....  
the last logs created is:

2023-02-14 07:11:11.460 DEBUG (MainThread) [wyzeapy.services.update_manager] Updating device: Front Door
2023-02-14 07:11:11.460 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/wyzeapy/services/update_manager.py", line 95, in update_next
    await updater.update() # It will only update if it is time for it to update. Otherwise it just reduces its update_in counter.
  File "/usr/local/lib/python3.10/site-packages/wyzeapy/services/update_manager.py", line 39, in update
    DeviceUpdater.mutex.acquire()
AttributeError: type object 'DeviceUpdater' has no attribute 'mutex'

**Comment by JoeSchubert** [comment]
I think I missed something when I was adding a mutex to force things into a bottleneck for throttling purposes... Though I didn't have any errors in testing.

I assume this pr that is pending merging is intended to address this.

https://github.com/JoshuaMulliken/wyzeapy/pull/64

**Comment by JoshuaMulliken** [comment]
@JoeSchubert that is correct @dave-dube can you test the latest beta and see if it is working for you?

**Comment by dave-dube** [comment]
@JoeSchubert @JoshuaMulliken  i did few basic tests with your new beta 0.1.18b2 and everything works fine.  So i would say this issue is fixed!  Thanks for your great work guys.  Appreciated!

**Comment by JoeSchubert** [comment]
Closing this as resolved.
