### ISSUE TITLE
[Feature Request]  Siren disappeared in last update

### ISSUE THREAD

**Issue by janfajessen** [JoshuaMulliken/ha-wyzeapi#468]
The Siren and Motion detection of the last integration in the Wyze Cam v3 have disappeared.  When updating to the latest version of HA in March, it warning me that the wyze api was incorrect and I had to update.  The only reason I was using this integration was so I could activate the Siren.  I hope you can fix it and it's available again.  You have done a great job.  If in the end it is not possible I will uninstall it.  Thank you

**Comment by brg468** [comment]
What version of the integration are you running? I still have both siren and motion detection on 0.1.17 and 0.1.19.

**Comment by janfajessen** [comment]
Version 0.1.19

**Comment by brg468** [comment]
![379779A2-11DE-40F4-B31B-666F37EED5AD](https://user-images.githubusercontent.com/19143191/223587137-8efa1c6c-b10e-4819-a319-0a483c1d95c4.jpeg)

Is your camera a different model number?

**Comment by janfajessen** [comment]
Yes, Same model. You can test if you hear the Siren by activating the from HA.  I've tried it and it doesn't work for me.  I will try in a few days
