### ISSUE TITLE
[Bug] Camera's Motion, Notification, & Siren are Unavailable. 

### ISSUE THREAD

**Issue by Ace0510** [JoshuaMulliken/ha-wyzeapi#470]
**Describe the bug**
 Camera's **Motion, Notification, & Siren are Unavailable** after upgrading to **0.5.19** Additionally, the Floodlight now shows in cameras without it.

**To Reproduce**
Is there any way to reload a previous version?

<img width="454" alt="image" src="https://user-images.githubusercontent.com/34573996/224734501-e22365f4-5b44-4ea4-8e67-d3d2736f804d.png">
<img width="767" alt="image" src="https://user-images.githubusercontent.com/34573996/224735227-e2eea483-81c8-4688-8999-74edfd5fe8e4.png">

**Expected behavior**
To operate correctly

**System configuration**
Home Assistant 2023.3.3
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.0 - latest

**home-assistant.log**
See attached
[home-assistant_wyzeapi_2023-03-13T14-44-38.521Z.zip](https://github.com/JoshuaMulliken/ha-wyzeapi/files/10958555/home-assistant_wyzeapi_2023-03-13T14-44-38.521Z.zip)

  logs:
    custom_components.wyzeapi: debug

For additional information see the readme: https://github.com/JoshuaMulliken/ha-wyzeapi#reporting-an-issue
-->

```
<PUT YOUR LOG HERE>
```

**Comment by Ace0510** [comment]
After updating to 2023.3.5 motion, notifications and siren are available. However, the camera motion is displayed as a switch. How can I change it to a sensor?

**Comment by brg468** [comment]
The switch is to toggle motion detection on/off, not a sensor.
