### ISSUE TITLE
[Bug] <short description of issue>

### ISSUE THREAD

**Issue by Ace0510** [JoshuaMulliken/ha-wyzeapi#473]
**Describe the bug**

After updating to Home Assistant 2023.3.6 Motion Detection, Notifications and Siren no longer work 

**To Reproduce**

**Expected behavior**

**System configuration**

Home Assistant 2023.3.6
Supervisor 2023.03.3
Operating System 9.5
Frontend 20230309.1 - latest

**home-assistant.log**

**Comment by brg468** [comment]
I see this is the 2nd time you’ve opened this issue. Is it always after an HA upgrade and what fixed it last time? Have you tried totally removing and reinstalling the integration?

**Comment by Ace0510** [comment]
No, but resetting and reloading HA appears to resolve the issue. So I am not sure how to replicate it. Thanks for your quick response. 😎
