### ISSUE TITLE
[Bug] Can't add as custom repository

### ISSUE THREAD

**Issue by AkshatShah1** [JoshuaMulliken/ha-wyzeapi#49]
Hi, I am new to Home Assistant so forgive me if I am overlooking something simple, however, when I try to follow the instructions in README, I get the following error in the System Log:

20-05-15 22:20:13 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/JoshuaMulliken/ha-wyzebulb repository

20-05-15 22:20:15 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/87977a50/repository.json: [Errno 2] No such file or directory: '/data/addons/git/87977a50/repository.json'

20-05-15 22:20:15 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/87977a50/repository.json

**Comment by JoshuaMulliken** [comment]
Hmm. That looks like a HACS issue have you submitted an issue there?

**Comment by AkshatShah1** [comment]
I'll try and see what they say over there, thank you

**Comment by AkshatShah1** [comment]
Okay, so apparently I was assuming that I wouldn't have to install HACS and I thought it was built into Hassio but I was wrong and so I installed HACS and added this as a custom repo. However, now it shows up as a new repository but after selecting a version and hitting install nothing happens.

**Comment by JoshuaMulliken** [comment]
Hmm that still sounds like a HACS issue. Sorry man
