### ISSUE TITLE
Lock not showing

### ISSUE THREAD

**Issue by jscherry** [JoshuaMulliken/ha-wyzeapi#53]
I've just installed version 4.2 and have also tried the 4.3 beta and the wyze lock isn't showing up under devices or entities. I have the lock calibrated properly and it works well with the wyze app.

**System configuration**
I'm running hassio (HA supervised) on a VM running Ubuntu with docker. Other details below:
docker | true
-- | --
hassio | true
host_os | Ubuntu 18.04.4 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 5.3.0-53-generic
python_version | 3.7.7
supervisor | 224
timezone | America/Chicago
version | 0.110.3
virtualenv | false
wyzeapi version: 4.2 

**Describe the bug**
Nothing is showing up for the lock? I also have the sense unit running with this custom component
https://github.com/kevinvincent/ha-wyzesense. I have been using it for a year with motion sensors and door contacts without problems. I have the USB sense adapter connected to my server the VM is on. I also have wyze pan cams with the rtsp firmware and one of the Pan cams has a wyze sense plugged into the back of the camera. The cameras and lock are connected to my wyze account and the motions and door contacts just connect through HA. Do I need disable it and only use your api version alone or can they both run at the same time?
This is the config for the motions and door contacts:
binary_sensor:
    - platform: wyzesense
      device: "auto"
      initial_state:
        77793176: "on"
        77793193: "off"

**Expected behavior**
Be able to see the status of the wyze lock.

**configuration.yaml**
wyzeapi:
    username: wyze email
    password: wyze password
```

**home-assistant.log**
logger:
  default: warning
  logs: 
      custom_components.wyzeapi: debug

Logs:
The only logs I see are warnings for bulbs and switches which I have neither?
Log Details (WARNING)
Logger: homeassistant.components.light
Source: components/light/__init__.py:451
Integration: Light (documentation, issues)
First occurred: 10:38:28 PM (1 occurrences)
Last logged: 10:38:28 PM

Light is deprecated, modify WyzeBulb to extend LightEntity

Log Details (WARNING)
Logger: homeassistant.components.switch
Source: components/switch/__init__.py:125
Integration: Switch (documentation, issues)
First occurred: 10:38:29 PM (1 occurrences)
Last logged: 10:38:29 PM

SwitchDevice is deprecated, modify WyzeSwitch to extend SwitchEntity
```

**Comment by jscherry** [comment]
just changed logger to default: info and the logs are the same.

**Comment by jfarmer08** [comment]
@jscherry The changes for the lock have not made it into the release or Beta release on HACS. If you want to test the lock you will need follow the manual Installation. 

@JoshuaMulliken Will update the HACS repo soon.

**Comment by JoshuaMulliken** [comment]
You can also select master in HACS that will be the most bleeding edge code and right now it includes the lock

**Comment by jfarmer08** [comment]
@JoshuaMulliken  Good call I forgot about that.

**Comment by jscherry** [comment]
Got it working thanks. I know very little coding but if I can help in any way to get the lock unlock functions working please let me know.

**Comment by kdoh82** [comment]
some bad news. i got fiddler set up on my network and was able to connect
my phone through it try and sniff some of the api commands from the
lock/gateway and it does not work for the lock. i can see all the api calls
for the other domains but the minute i try to bring up the lock or the
gateway in the app, the app throws and internal server error and nothing
happens. wondering if others are seeing the same thing.

**Comment by jfarmer08** [comment]
@kdoh82 Can you try and adding a Rule - Shortcut, Schedule or Device Trigger for the lock. This might allow you to see something new. 

When i found on the cameras was with a shortcut the API was running a Run_action command and I was able to repeat it to turn it on and off. If by chance it does show something for the run_action we would need the action_key parameter. 

https://api.wyzecam.com/app/v2/auto/run_action

**Comment by JoshuaMulliken** [comment]
@kdoh82 @jfarmer08  please move this conversation to the main feature thread. I am going to be closing this one as it appears to be resolved
