### ISSUE TITLE
[Feature Request] Assign to areas

### ISSUE THREAD

**Issue by siobhter** [JoshuaMulliken/ha-wyzeapi#56]
**Is your feature request related to a problem? Please describe.**
No problems, this is working as it should. Excellent work, by the way. 

**Describe the solution you'd like**
I wondered if there is a way to assign the Wyze switches to an area?

**Comment by jfarmer08** [comment]
@siobhter I can look into this for you, but It might take some time.

**Comment by siobhter** [comment]
That would be awesome! How do I send you a beer for the trouble?

**Comment by jfarmer08** [comment]
No need this would be helpful for me too.

**Comment by siobhter** [comment]
That's awesome, let me know if you need someone to test.

**Comment by JoshuaMulliken** [comment]
Yep, we might have to transition to describing the "entities" as "devices" instead. The only things that can be assigned to an area are "devices". It might not be that hard because a device is just a collection of entities. Maybe we can just wrap what we already have in a device object.
