### ISSUE TITLE
[Feature Request] Low battery status as attribute for lock

### ISSUE THREAD

**Issue by kdoh82** [JoshuaMulliken/ha-wyzeapi#60]
**Is your feature request related to a problem? Please describe.**
 No.

**Describe the solution you'd like**

My lock currently has a low battery alert on the app that normally doesn't appear so I'm thinking it might be a good idea to add that to the attributes for the lock in HA so we can trigger against it, notifications, etc. 

I can help by running calls and getting information as needed if someone thinks this is a good feature add.

**Comment by markrickert** [comment]
This is a great idea to track this attribute on the lock. It would be useful information in a HA dashboard.

**Comment by jfarmer08** [comment]
@kdoh82 We should add this if we can get the information from the API

**Comment by kdoh82** [comment]
Looks like this info is only available through the MQTT data or the page
that doesn't display when I call the page connecting through Fiddler.

**Comment by jfarmer08** [comment]
Thanks for Checking. We can close this request.
