### ISSUE TITLE
Home Assistant Integration for Wyze Bulbs, Switches, Sensors and Lock

### ISSUE THREAD

**Issue by yfaber** [JoshuaMulliken/ha-wyzeapi#61]
Did you guys merge the Wyzesense and Wyzeapi into the same project? After installing this update the other Wyzesense stopped working.

**Comment by Caustik314** [comment]
I am running both integrations, but on **_this_** one I use "sensors: false" under my config in  configuration.yaml

**Comment by jfarmer08** [comment]
@Caustik314 that would be the correct way to do it, but even if you don't call out sensors: false it will not cause an issue with a different integration. Thank you for testing.
