### ISSUE TITLE
Wyze Lock Battery Level Attribute

### ISSUE THREAD

**Issue by terrycarlin** [JoshuaMulliken/ha-wyzeapi#62]
**Is your feature request related to a problem? Please describe.**

Being able to write an automation to monitor the battery level on the Wyze Lock will help prevent Wyze Lock failures.
**Describe the solution you'd like**

Would like to have a battery attribute for Wyze Lock indicating percentage of battery charge
**Describe alternatives you've considered**

**Additional context**

The battery level is displayed in the Wyze app so it seems to be available.

**Comment by jfarmer08** [comment]
This was already discuss and currently unable to be supported. 

[https://github.com/JoshuaMulliken/ha-wyzeapi/issues/60](https://github.com/JoshuaMulliken/ha-wyzeapi/issues/60)
