### ISSUE TITLE
[Bug] Wye lock api not found error

### ISSUE THREAD

**Issue by shshnkvadali** [JoshuaMulliken/ha-wyzeapi#64]
** Wyze lock unlock/lock api errors **

```<ClientResponse(https://beta-api.wyzecam.com/app/v2/auto/run_action) [404 Not Found]>```

**To Reproduce**
1. Enable debug logs
2. Unlock the wyze lock
3. Print 'resp' variable

**Expected behavior**
Unlock the lock

**System configuration**
System: Docker
HA Version: v0.112.3
WyzeApi Version: v0.5.0

**configuration.yaml**
```yaml
wyzeapi:
  username: <email>
  password: <password>

logger:
  default: warning
  logs:
    custom_components.wyzeapi: debug
```

**home-assistant.log**

```
2020-07-07 09:02:03 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.wyze_request] <ClientResponse(https://beta-api.wyzecam.com/app/v2/auto/run_action) [404 Not Found]>
<CIMultiDictProxy('Content-Type': 'text/html; charset=us-ascii', 'Date': 'Tue, 07 Jul 2020 13:02:05 GMT', 'Server': 'Microsoft-HTTPAPI/2.0', 'Content-Length': '315', 'Connection': 'keep-alive')>

2020-07-07 09:02:03 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 204, in async_do_request
    return await WyzeRequest(url, payload).async_get_response()
  File "/config/custom_components/wyzeapi/wyzeapi/wyze_request.py", line 47, in async_get_response
    data = await resp.json()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1031, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=us-ascii', url='https://beta-api.wyzecam.com/app/v2/auto/run_action
```

**Comment by JoshuaMulliken** [comment]
@jfarmer08 Could they have changed the endpoint to a stable version? Are you experiencing the same issue?

**Comment by jfarmer08** [comment]
We cannot support Locking and Unlocking the lock. We need to remove to code and report something else.. 

So the question, is the lock showing in HA with the correct States?

**Comment by JoshuaMulliken** [comment]
Oh that's right. I wonder if we can add a flag that tells HA that the lock doesn't support that.

**Comment by jfarmer08** [comment]
Yeah.. i am sure we can.. I have been to busy with actual work that i have not had time to do anything else.. Maybe we can sync up on Discord or something.. 

I don't have a Wyze Lock so i cannot do anymore debugging for it. We i added this  @yfaber Helped me out with giving me access to his.

**Comment by JoshuaMulliken** [comment]
@jfarmer08 I'll do some research. I just moved so my system isn't set up yet. It might be good for us to connect with @yfaber. I'll PM you my discord name

**Comment by shshnkvadali** [comment]
I'd like to help if its feasible. Is there a development guide you can point me to?

**Comment by jfarmer08** [comment]
@shshnkvadali Check out the link below to get started. 

[Home Assistant Development](https://developers.home-assistant.io/docs/development_index/)

**Comment by vincesima** [comment]
Also have a Wyze Lock/HA Setup and am a developer, would also be available for help/testing. As current, only reporting status on HA restart, and cannot lock/unlock. I have also had it connecting thru ZHA, which was able to lock/unlock but won't report state.

**Comment by jfarmer08** [comment]
@JoshuaMulliken @vincesima 
Maybe someone can add support for ZHA in the lock/unlock commands in WyzeAPI. Since they can control it and we can see the status.

**Comment by JoshuaMulliken** [comment]
I disabled the lock and unlock and set the system to give the user a notification if they try to use the lock and unlock. If you want to try this out for me then please use the master branch. I am going to be publishing a beta with this soon.

**Comment by JoshuaMulliken** [comment]
@everyone the beta is now avaliable

**Comment by JoshuaMulliken** [comment]
I would actually recommend creating a template lock if you want to get the status of the door with this integration and do the control using ZHA: [https://www.home-assistant.io/integrations/lock.template/](https://www.home-assistant.io/integrations/lock.template/)
