### ISSUE TITLE
[Feature Request] Support for Wyze Plugs

### ISSUE THREAD

**Issue by n8carrier** [JoshuaMulliken/ha-wyzeapi#67]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I'd like to be able to use Home Assistant to control Wyze Plug devices

**Describe alternatives you've considered**
Integrating via IFTTT

**Additional context**
N/A

**Comment by JoshuaMulliken** [comment]
This is currently supported. They are known as switches. Please check the readme

**Comment by n8carrier** [comment]
Sorry didn't realize that was the same thing. Thank you!

**Comment by JoshuaMulliken** [comment]
No worries @n8carrier!
