### ISSUE TITLE
[Question] Device id has the same value for everyone using the integration

### ISSUE THREAD

**Issue by dimmanramone** [JoshuaMulliken/ha-wyzeapi#68]
I was looking into the code and I realise that everyone that is using this integration, have the same device id (guid).

Any particular reason that it is a hard coded value?

**Comment by JoshuaMulliken** [comment]
It is one that works that isn't associated with my phone 🤷

**Comment by dimmanramone** [comment]
@JoshuaMulliken How do you get your own mobile device_id? Is there anyway? If it is a simple way then maybe device_id can be changed to a variable instead.

**Comment by JoshuaMulliken** [comment]
@dimmanramone It could be changed. You have to MITM your connection between your phone and the wyze servers to find it. I have not seen any downsides to people sharing this id other than possibly polluting their internal analytics.

**Comment by dimmanramone** [comment]
@JoshuaMulliken I did try with wireshark but no luck there I couldn't find my device id :/ Even if there are not any downsides having a unique personal device id, it just feels better to do so :)

**Comment by jfarmer08** [comment]
You can use Fildder with a proxy to get the info you are looking for although I agree with @JoshuaMulliken about not changing it. One down side is Wyze could block you thinking it's spam with HA hitting the api. We don't make the calls in the same way as wyze does so even if you do change the key they still now it's not the official Wyze app requesting this info. Same goes for this key it could be block at any point. Good luck.

**Comment by JoshuaMulliken** [comment]
You cannot do that with Wireshark. It uses https so you need to use an intercepting proxy like burpsuite, fiddler or mitmproxy.
