### ISSUE TITLE
intergration and platforms could not be set up

### ISSUE THREAD

**Issue by skylark332** [JoshuaMulliken/ha-wyzeapi#70]
I have installed the repository and added the below config to yaml but when i restart HA I keep getting a notification that the wyzeapi could not be setup? Is the below config off?

wyzeapi:
  username: "wyze email"
  password: "wyze PW"

**Comment by Ryan911199** [comment]
I have a similar problem, I can't get mine to show up at all. I installed the repository and it seemed fine, but I have plugged in the TX (little USB box) and my home assistant release won't find it. it just keeps blinking blue and yellow no matter what I do.

**Comment by Ryan911199** [comment]
also make sure you have a wyze account set up with that login before hand.

**Comment by JoshuaMulliken** [comment]
@skylark332 Can you send us your debug logs? instructions are in the readme: https://github.com/JoshuaMulliken/ha-wyzeapi

**Comment by JoshuaMulliken** [comment]
I will be closing this issue as it seems to be stale. If you come back with the logs as requested please create a new issue.
