### ISSUE TITLE
[Bug] v0.5.3 typo in switch.py available spelled as avaliable stops switches from working

### ISSUE THREAD

**Issue by fuzzyogic** [JoshuaMulliken/ha-wyzeapi#79]
**Describe the bug**
Typo in below sections:
  Section 1:
    custom_components\wyzeapi\switch.py
    line 65
      current:
        return self.__switch.avaliable
      fix:
        return self.__switch.available

  Section 2:
    custom_components\wyzeapi\wyzeapi\devices\switch.py
    line 9:
      current:
        avaliable: int
      fix:
        available: int
    line 30:
      current:
        "P5": self.avaliable,
      fix:
        "P5": self.available,

**To Reproduce**
1. Install add-on
2. In HA Overview, wyze switches are unavailable

**Comment by ha20** [comment]
Also line 65 in /config/custom_components/wyzeapi/switch.py

**Comment by 1h8fulkat** [comment]
Confirmed the above edits resolve this issue.

**Comment by fortwally** [comment]
Confirmed the above edits resolve this issue.

**Comment by JoshuaMulliken** [comment]
Thank you everyone! I have published a new release that fixes this problem
