### ISSUE TITLE
Wyze lamp does not respond to HA commands or automation

### ISSUE THREAD

**Issue by lazzerbeam** [JoshuaMulliken/ha-wyzeapi#81]
[WyzeApi_failed_light_control_HA.txt](https://github.com/JoshuaMulliken/ha-wyzeapi/files/5165404/WyzeApi_failed_light_control_HA.txt)

Hello,
The lamp worked initially after integration. But now, light seems to not respond to HA turn_on/off service or even direct toggles.
Guessing issue is with the Wyze server not capturing HA requests. Control from the WYZE app works without an issue.
Please see attached logs of repeated trials to toggle the lamp. All failed except one turn OFF. Thanks.

**Comment by JoshuaMulliken** [comment]
You are running an old version of the integration. Please update and then provide new debug logs. The latest is v0.5.6 you are running v0.5.1

**Comment by lazzerbeam** [comment]
working after the update. Installed in manually. Thanks!
