### ISSUE TITLE
Smooth Transition of light from x to y percent

### ISSUE THREAD

**Issue by whwar9739** [JoshuaMulliken/ha-wyzeapi#86]
I was wondering if the wyzeapi supports the light transition option at all, or if wyze bulbs are even capable of this option.
I would like to be able to setup node-red automations for sunrise like effect and slowly fade the lights up over a given period of time.
Thanks!

**Comment by JoshuaMulliken** [comment]
Not to my knowledge unfortunately. Sorry!
