### ISSUE TITLE
[Feature Request] Wyze Thermostat

### ISSUE THREAD

**Issue by JOHLC** [JoshuaMulliken/ha-wyzeapi#87]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add support for the upcoming Wyze Thermostat https://wyze.com/wyze-thermostat.html

**Describe alternatives you've considered**
Nest

**Additional context**
https://support.wyzecam.com/hc/en-us/articles/360049453252-Introducing-Wyze-Thermostat
https://wyze.com/wyze-thermostat.html
https://support.wyzecam.com/hc/en-us/categories/360004059652-Wyze-Thermostat

**Comment by JoshuaMulliken** [comment]
Hello, @JOHLC support may come once it is released but I will not be purchasing one because I am renting so I will need help from contributors in order to implement this. We need to know what API calls are made to the application and what properties are shown by the application.

Beta testers will also be needed to get this tested and working

**Comment by JOHLC** [comment]
Thanks for your feedback! I am also renting but just don't care ;) 

The release is still a ways out, but I still may or may not purchase one depending. 

Thanks for your time and effort

**Comment by LordNex** [comment]
I’m also looking at getting one of these. I own my house and it’s fully kitted. Actually building new 6 in 1 NodeMCU multi sensors this weekend that will come in handy later. 

Once I get one and setup I’ll let you know, then just walk me through what you need me to gather. I’m not a full time programmer but I’ve been in the IT Networking field for over 20 years so I’m sure I can figure out how to get what you need anyway. This would be a nice option over a Nest or more expensive and cloud based solution anyway. Thanks again for all your kick ass work man! 👍🤓😎

**Comment by Lukejb14** [comment]
When my preorder gets here, let me know anything I can provide to you.

**Comment by JoshuaMulliken** [comment]
Yall can follow the progress on this branch https://github.com/JoshuaMulliken/ha-wyzeapi/tree/implement-wyze-thermostat

**Comment by JoshuaMulliken** [comment]
Discussion thread here: https://github.com/JoshuaMulliken/ha-wyzeapi/discussions/103

**Comment by shauntarves** [comment]
@JOHLC @LordNex @Lukejb14 

I have been working with @JoshuaMulliken to reverse-engineer a generic wyze API. I've finally cracked what they're doing in their newer requests and how they hit their own API. We now have full support for the bulbs, plugs/switches, and the new vacuum. I would love to add support for more devices, but I need someone who has these devices to be willing to work with me directly and share some access/data to I can make the code work. If you're interested in helping out, please email `shaun <at> tarves <dot> net`

**Comment by sspencer10** [comment]
> @JOHLC @LordNex @Lukejb14
> 
> I have been working with @JoshuaMulliken to reverse-engineer a generic wyze API. I've finally cracked what they're doing in their newer requests and how they hit their own API. We now have full support for the bulbs, plugs/switches, and the new ?vacuum. I would love to add support for more devices, but I need someone who has these devices to be willing to work with me directly and share some access/data to I can make the code work. If you're interested in helping out, please email `shaun <at> tarves <dot> net`

So it seems you have this figured out now, can you maybe make a PR to get the thermostat working in ha-wyzeapi?

**Comment by shauntarves** [comment]
@sspencer10 I have spoken with Josh at length about integrating my work and he said he wants to go in a different direction and implement his own client, so I will not be doing this.

Feel free to submit your own PR if you want.

**Comment by LordNex** [comment]
> Thanks for your feedback! I am also renting but just don't care ;) 
> 
> 
> 
> The release is still a ways out, but I still may or may not purchase one depending. 
> 
> 
> 
> Thanks for your time and effort

Just so you know, they work under standard ZHA until Josh can finish the API integration. If you need help, let me know. Super easy to setup and super helpful!

**Comment by sspencer10** [comment]
> @sspencer10 I have spoken with Josh at length about integrating my work and he said he wants to go in a different direction and implement his own client, so I will not be doing this.
> 
> 
> 
> Feel free to submit your own PR if you want.

I try to figure something out, just really short on time at the moment

**Comment by JoshuaMulliken** [comment]
@everyone please take a look at the latest beta and help me test this feature! It is almost ready for prime-time!
