### ISSUE TITLE
[Bug] MFA Causes Invalid Config error.

### ISSUE THREAD

**Issue by bed428** [JoshuaMulliken/ha-wyzeapi#88]
**Describe the bug**
If you have MFA enabled on your account, it causes the following error. 

Invalid config
The following integrations and platforms could not be set up: 
 - wyzeapi
Please check your config

**To Reproduce**
1. Enable MFA on your Wyze account, try to login.

Turned off two-step verification. 
Verified working. 

Not sure what the solution would be - just wanted to make everyone aware if you're looking at bugs to figure this out.

**Comment by JoshuaMulliken** [comment]
Yes this is explicitly stated in the readme.
