### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by bjs-pdx** [JoshuaMulliken/ha-wyzeapi#90]
**Is your feature request related to a problem? Please describe.**
Setup clarification....

wyzeapi:
  username: <email for wyze>
  password: <password for wyze>
  sensors: false
  light: false
  switch: false
  lock: false

Documentation is unclear.  Does false mean ignore the item?  Would true include them?

**Comment by JoshuaMulliken** [comment]
Yes that is correct

**Comment by JoshuaMulliken** [comment]
If you don't include an entry it will include it by default
