### ISSUE TITLE
[Feature Request] make it local like wyze sense

### ISSUE THREAD

**Issue by VajraCool** [JoshuaMulliken/ha-wyzeapi#95]
I am about to try this, but I am wondering as we are giving username and pwd of wyze, this is not local . can it make local like wyze sense?
**Wyze sense canbe done local using this repo https://github.com/kevinvincent/ha-wyzesense**

**Comment by JoshuaMulliken** [comment]
This is not possible. This integration is cloud-connected and unfortunately, it is currently not possible to connect to the various wyze devices such as the switch and the bulbs locally.
