### ISSUE TITLE
Name Changes of Wyze Devices

### ISSUE THREAD

**Issue by bjs-pdx** [JoshuaMulliken/ha-wyzeapi#97]
I've used the Wyze application to do two things:  Changed a contact sensor name;  removed and added back a motion sensor with a different name.  In HomeAssitant the names remain unchanged.  How can I force the names to update?

**Comment by JoshuaMulliken** [comment]
Go to the entities page in configuration and change the entity id or the name
![image](https://user-images.githubusercontent.com/36283247/100885004-27048d00-3480-11eb-9b23-834dcef1babf.png)
