### ISSUE TITLE
[Feature Request] Assign entities to devices so they can be attached to areas

### ISSUE THREAD

**Issue by FattySparks** [JoshuaMulliken/ha-wyzeapi#98]
I'd like to be able to add my devices to the areas that I have set up for my home. Since the objects are brought in as entities instead of devices, this option isn't available

**Comment by JoshuaMulliken** [comment]
This is now officially supported in Home Assistant Core 2020.12!!!! https://www.home-assistant.io/blog/2020/12/13/release-202012/#assign-areas-to-entities-and-readable-area-ids
